window.repositoryObject = {
  columns_custom_fields: [],
  relations_custom_fields: [],
  unique_keys_custom_fields: [],
  triggers_custom_fields: [],
  columns: [
    {
      id: "column-2241",
      object_id: "column-2241",
      name: "PLANS",
      name_without_path: "PLANS",
      description: "Plan S",
      is_pk: true,
      is_identity: false,
      data_type: "varchar",
      data_length: "10",
      is_nullable: false,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-2242",
      object_id: "column-2242",
      name: "PLANDESC",
      name_without_path: "PLANDESC",
      description: "Plan DESC",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "40",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-2243",
      object_id: "column-2243",
      name: "EFFECTIVEDATEENDS",
      name_without_path: "EFFECTIVEDATEENDS",
      description: "Effective Date Ends",
      is_pk: false,
      is_identity: false,
      data_type: "datetime",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-2244",
      object_id: "column-2244",
      name: "DOW",
      name_without_path: "DOW",
      description: "Effective Days of the Week T/F positional Sun-Sat",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "7",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-2245",
      object_id: "column-2245",
      name: "TIME1",
      name_without_path: "TIME1",
      description: "Begin Time",
      is_pk: false,
      is_identity: false,
      data_type: "int",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-2246",
      object_id: "column-2246",
      name: "EFFECTIVEDATEBEGINS",
      name_without_path: "EFFECTIVEDATEBEGINS",
      description: "Effective Date Begins",
      is_pk: false,
      is_identity: false,
      data_type: "datetime",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-2247",
      object_id: "column-2247",
      name: "TIME2",
      name_without_path: "TIME2",
      description: "End Time",
      is_pk: false,
      is_identity: false,
      data_type: "int",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
  ],
  relations: [
    {
      name: "FK_PLANSRAS_PLANS",
      title: null,
      description: null,
      is_user_defined: false,
      foreign_table: "PLANSRAS",
      foreign_table_show_schema: "dbo.PLANSRAS",
      foreign_table_verbose: "PLANSRAS",
      foreign_table_verbose_show_schema: "dbo.PLANSRAS",
      foreign_table_object_id: "t112",
      primary_table: "PLANS",
      primary_table_show_schema: "dbo.PLANS",
      primary_table_verbose: "PLANS",
      primary_table_verbose_show_schema: "dbo.PLANS",
      primary_table_object_id: "t106",
      pk_cardinality: "1x",
      fk_cardinality: "mx",
      constraints: [
        {
          primary_column_path: null,
          primary_column: "PLANS",
          foreign_column_path: null,
          foreign_column: "PLANS",
        },
      ],
      custom_fields: {},
    },
  ],
  unique_keys: [
    {
      name: "PK_PLANS",
      description: null,
      is_pk: true,
      is_user_defined: false,
      columns: [
        {
          path: null,
          name_without_path: "PLANS",
          name: "PLANS",
          column_id: 2241,
        },
      ],
      custom_fields: {},
    },
  ],
  triggers: [],
  dependencies: {
    uses: [],
    used_by: [
      {
        object_name: "PLANS",
        object_name_show_schema: "dbo.PLANS",
        object_type: "TABLE",
        object_id: "t106",
        type: "NORMAL",
        object_user_defined: false,
        user_defined: false,
        children: [
          {
            object_name: "PLANSRAS",
            object_name_show_schema: "dbo.PLANSRAS",
            object_type: "TABLE",
            object_id: "t112",
            type: "RELATION",
            pk_cardinality: "1x",
            fk_cardinality: "mx",
            object_user_defined: false,
            user_defined: false,
            children: [],
          },
        ],
      },
    ],
  },
  object_id: "t106",
  name: "PLANS",
  subtype: "TABLE",
  is_user_defined: false,
  description:
    '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\r\n                <html xmlns="http://www.w3.org/1999/xhtml">\r\n                    <head>\r\n                        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><title>\r\n                        </title>\r\n                        <style type="text/css">\r\n                            .cs2654AE3A{text-align:left;text-indent:0pt;margin:0pt 0pt 0pt 0pt}\r\n                            .cs416E45A4{color:#000000;background-color:transparent;font-family:\'Segoe UI\';font-size:10pt;font-weight:normal;font-style:normal;}\r\n                        </style>\r\n                    </head>\r\n                    <body>\r\n                        <p class="cs2654AE3A"><span class="cs416E45A4">PLANS Information</span></p></body>\r\n                </html>',
  summary: [
    {
      field: "Documentation",
      value: { _type: "link", name: "SUN RIDGE SYSTEMS", id: "d1" },
    },
    { field: "Schema", value: "dbo" },
    { field: "Name", value: "PLANS" },
    { field: "Type", value: "Table" },
  ],
  script: "",
  imported_at: "2024-10-01 02:34",
};
