window.repositoryObject = {
  columns_custom_fields: [],
  relations_custom_fields: [],
  unique_keys_custom_fields: [],
  triggers_custom_fields: [],
  columns: [
    {
      id: "column-3232",
      object_id: "column-3232",
      name: "SUBID",
      name_without_path: "SUBID",
      description: "Subpoena ID",
      is_pk: true,
      is_identity: true,
      data_type: "numeric",
      data_length: "18, 0",
      is_nullable: false,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3233",
      object_id: "column-3233",
      name: "NAME",
      name_without_path: "NAME",
      description: "Name",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "48",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3234",
      object_id: "column-3234",
      name: "COURTCASE",
      name_without_path: "COURTCASE",
      description: "Court Case",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "60",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3235",
      object_id: "column-3235",
      name: "COURT",
      name_without_path: "COURT",
      description: "Judicial District",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "60",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3236",
      object_id: "column-3236",
      name: "JUDGE",
      name_without_path: "JUDGE",
      description: "Judge",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "60",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3237",
      object_id: "column-3237",
      name: "COURTDATE",
      name_without_path: "COURTDATE",
      description: "Court Date",
      is_pk: false,
      is_identity: false,
      data_type: "datetime",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3238",
      object_id: "column-3238",
      name: "COURTTIME",
      name_without_path: "COURTTIME",
      description: "Court Time",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "5",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3239",
      object_id: "column-3239",
      name: "CASEN",
      name_without_path: "CASEN",
      description: "Case #",
      is_pk: false,
      is_identity: false,
      data_type: "int",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [{ id: "t65", name: "CASES", name_show_schema: "dbo.CASES" }],
      linked_lookup: null,
    },
    {
      id: "column-3240",
      object_id: "column-3240",
      name: "REFNUM",
      name_without_path: "REFNUM",
      description: "Reference Number",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "20",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3241",
      object_id: "column-3241",
      name: "CMT",
      name_without_path: "CMT",
      description: "CMT",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "275",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3242",
      object_id: "column-3242",
      name: "RCVDATE",
      name_without_path: "RCVDATE",
      description: "Date Rcvd",
      is_pk: false,
      is_identity: false,
      data_type: "datetime",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3243",
      object_id: "column-3243",
      name: "RCVTIME",
      name_without_path: "RCVTIME",
      description: "Received Time",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "5",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3244",
      object_id: "column-3244",
      name: "RCVDBY",
      name_without_path: "RCVDBY",
      description: "Received By",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "40",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3245",
      object_id: "column-3245",
      name: "ENTERDATE",
      name_without_path: "ENTERDATE",
      description: "Date Entered",
      is_pk: false,
      is_identity: false,
      data_type: "datetime",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3246",
      object_id: "column-3246",
      name: "ENTERTIME",
      name_without_path: "ENTERTIME",
      description: "Entered Time",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "5",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3247",
      object_id: "column-3247",
      name: "ENTEREDBY",
      name_without_path: "ENTEREDBY",
      description: "Entered By",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "40",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3248",
      object_id: "column-3248",
      name: "ACKDATE",
      name_without_path: "ACKDATE",
      description: "Acknowledged Date",
      is_pk: false,
      is_identity: false,
      data_type: "datetime",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3249",
      object_id: "column-3249",
      name: "ACKTIME",
      name_without_path: "ACKTIME",
      description: "Acknowledged Time",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "5",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3250",
      object_id: "column-3250",
      name: "ACKED",
      name_without_path: "ACKED",
      description: "Acknowledged",
      is_pk: false,
      is_identity: false,
      data_type: "char",
      data_length: "1",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3251",
      object_id: "column-3251",
      name: "SIGNEDDATE",
      name_without_path: "SIGNEDDATE",
      description: "Signed by Date",
      is_pk: false,
      is_identity: false,
      data_type: "datetime",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3252",
      object_id: "column-3252",
      name: "SIGNEDTIME",
      name_without_path: "SIGNEDTIME",
      description: "Signed by Time",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "5",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3253",
      object_id: "column-3253",
      name: "RETURNDATE",
      name_without_path: "RETURNDATE",
      description: "Date Returned",
      is_pk: false,
      is_identity: false,
      data_type: "datetime",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3254",
      object_id: "column-3254",
      name: "RETURNED",
      name_without_path: "RETURNED",
      description: "Returned?",
      is_pk: false,
      is_identity: false,
      data_type: "char",
      data_length: "1",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3255",
      object_id: "column-3255",
      name: "SUBPERSID",
      name_without_path: "SUBPERSID",
      description: "Person Served (ID)",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "10",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3256",
      object_id: "column-3256",
      name: "RECALLREASON",
      name_without_path: "RECALLREASON",
      description: "Recalled Reason",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "60",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3257",
      object_id: "column-3257",
      name: "RECALLDATE",
      name_without_path: "RECALLDATE",
      description: "Recalled Date",
      is_pk: false,
      is_identity: false,
      data_type: "datetime",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3258",
      object_id: "column-3258",
      name: "SERVINGPERSONDATE",
      name_without_path: "SERVINGPERSONDATE",
      description: "Serving Person Date",
      is_pk: false,
      is_identity: false,
      data_type: "datetime",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3259",
      object_id: "column-3259",
      name: "SERVINGPERSONTIME",
      name_without_path: "SERVINGPERSONTIME",
      description: "Serving Person Time",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "5",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3260",
      object_id: "column-3260",
      name: "SERVINGPERSON",
      name_without_path: "SERVINGPERSON",
      description: "Serving Person",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "40",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3261",
      object_id: "column-3261",
      name: "DACASE",
      name_without_path: "DACASE",
      description: "DA Case",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "32",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3262",
      object_id: "column-3262",
      name: "SUBPOENATYPE",
      name_without_path: "SUBPOENATYPE",
      description: "Subpoena Type",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "10",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3263",
      object_id: "column-3263",
      name: "DAPHONE",
      name_without_path: "DAPHONE",
      description: "DA Phone",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "12",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3264",
      object_id: "column-3264",
      name: "DEFENDANT",
      name_without_path: "DEFENDANT",
      description: "Defendant",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "48",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3265",
      object_id: "column-3265",
      name: "CITATION",
      name_without_path: "CITATION",
      description: "Citation",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "20",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [
        { id: "t357", name: "CITATION", name_show_schema: "dbo.CITATION" },
      ],
      linked_lookup: null,
    },
    {
      id: "column-3266",
      object_id: "column-3266",
      name: "COURTROOM",
      name_without_path: "COURTROOM",
      description: "Court Room",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "32",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
  ],
  relations: [
    {
      name: "FK_SUBPOENA_CASES",
      title: null,
      description: null,
      is_user_defined: false,
      foreign_table: "SUBPOENA",
      foreign_table_show_schema: "dbo.SUBPOENA",
      foreign_table_verbose: "SUBPOENA",
      foreign_table_verbose_show_schema: "dbo.SUBPOENA",
      foreign_table_object_id: "t144",
      primary_table: "CASES",
      primary_table_show_schema: "dbo.CASES",
      primary_table_verbose: "CASES",
      primary_table_verbose_show_schema: "dbo.CASES",
      primary_table_object_id: "t65",
      pk_cardinality: "1x",
      fk_cardinality: "mx",
      constraints: [
        {
          primary_column_path: null,
          primary_column: "CASEN",
          foreign_column_path: null,
          foreign_column: "CASEN",
        },
      ],
      custom_fields: {},
    },
    {
      name: "FK_SUBPOENA_CITATION",
      title: null,
      description: null,
      is_user_defined: false,
      foreign_table: "SUBPOENA",
      foreign_table_show_schema: "dbo.SUBPOENA",
      foreign_table_verbose: "SUBPOENA",
      foreign_table_verbose_show_schema: "dbo.SUBPOENA",
      foreign_table_object_id: "t144",
      primary_table: "CITATION",
      primary_table_show_schema: "dbo.CITATION",
      primary_table_verbose: "CITATION",
      primary_table_verbose_show_schema: "dbo.CITATION",
      primary_table_object_id: "t357",
      pk_cardinality: "1x",
      fk_cardinality: "mx",
      constraints: [
        {
          primary_column_path: null,
          primary_column: "CITATION",
          foreign_column_path: null,
          foreign_column: "CITATION",
        },
      ],
      custom_fields: {},
    },
  ],
  unique_keys: [
    {
      name: "PK_SUBPOENA",
      description: null,
      is_pk: true,
      is_user_defined: false,
      columns: [
        {
          path: null,
          name_without_path: "SUBID",
          name: "SUBID",
          column_id: 3232,
        },
      ],
      custom_fields: {},
    },
  ],
  triggers: [],
  dependencies: {
    uses: [
      {
        object_name: "SUBPOENA",
        object_name_show_schema: "dbo.SUBPOENA",
        object_type: "TABLE",
        object_id: "t144",
        type: "NORMAL",
        object_user_defined: false,
        user_defined: false,
        children: [
          {
            object_name: "CASES",
            object_name_show_schema: "dbo.CASES",
            object_type: "TABLE",
            object_id: "t65",
            type: "RELATION",
            pk_cardinality: "1x",
            fk_cardinality: "mx",
            object_user_defined: false,
            user_defined: false,
            children: [],
          },
          {
            object_name: "CITATION",
            object_name_show_schema: "dbo.CITATION",
            object_type: "TABLE",
            object_id: "t357",
            type: "RELATION",
            pk_cardinality: "1x",
            fk_cardinality: "mx",
            object_user_defined: false,
            user_defined: false,
            children: [],
          },
        ],
      },
    ],
    used_by: [],
  },
  object_id: "t144",
  name: "SUBPOENA",
  subtype: "TABLE",
  is_user_defined: false,
  description:
    '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\r\n                <html xmlns="http://www.w3.org/1999/xhtml">\r\n                    <head>\r\n                        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><title>\r\n                        </title>\r\n                        <style type="text/css">\r\n                            .cs2654AE3A{text-align:left;text-indent:0pt;margin:0pt 0pt 0pt 0pt}\r\n                            .cs416E45A4{color:#000000;background-color:transparent;font-family:\'Segoe UI\';font-size:10pt;font-weight:normal;font-style:normal;}\r\n                        </style>\r\n                    </head>\r\n                    <body>\r\n                        <p class="cs2654AE3A"><span class="cs416E45A4">Need a description</span></p></body>\r\n                </html>',
  summary: [
    {
      field: "Documentation",
      value: { _type: "link", name: "SUN RIDGE SYSTEMS", id: "d1" },
    },
    { field: "Schema", value: "dbo" },
    { field: "Name", value: "SUBPOENA" },
    { field: "Type", value: "Table" },
  ],
  script: "",
  imported_at: "2024-10-01 02:34",
};
