window.repositoryObject = {
  columns_custom_fields: [],
  relations_custom_fields: [],
  unique_keys_custom_fields: [],
  triggers_custom_fields: [],
  columns: [
    {
      id: "column-3336",
      object_id: "column-3336",
      name: "INCTYPE",
      name_without_path: "INCTYPE",
      description: "INC Type",
      is_pk: true,
      is_identity: false,
      data_type: "varchar",
      data_length: "8",
      is_nullable: false,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3337",
      object_id: "column-3337",
      name: "NOTE",
      name_without_path: "NOTE",
      description: "Note",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "240",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3338",
      object_id: "column-3338",
      name: "QUESTION1",
      name_without_path: "QUESTION1",
      description: "Question1",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "240",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3339",
      object_id: "column-3339",
      name: "QUESTION2",
      name_without_path: "QUESTION2",
      description: "Question2",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "240",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3340",
      object_id: "column-3340",
      name: "QUESTION3",
      name_without_path: "QUESTION3",
      description: "Question3",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "240",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3341",
      object_id: "column-3341",
      name: "QUESTION4",
      name_without_path: "QUESTION4",
      description: "Question4",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "240",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3342",
      object_id: "column-3342",
      name: "QUESTION5",
      name_without_path: "QUESTION5",
      description: "Question5",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "240",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3343",
      object_id: "column-3343",
      name: "QUESTION6",
      name_without_path: "QUESTION6",
      description: "Question6",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "240",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3344",
      object_id: "column-3344",
      name: "QUESTION7",
      name_without_path: "QUESTION7",
      description: "Question7",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "240",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3345",
      object_id: "column-3345",
      name: "QUESTION8",
      name_without_path: "QUESTION8",
      description: "Question8",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "240",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3346",
      object_id: "column-3346",
      name: "QUESTION9",
      name_without_path: "QUESTION9",
      description: "Question9",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "240",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3347",
      object_id: "column-3347",
      name: "QUESTION10",
      name_without_path: "QUESTION10",
      description: "Question10",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "240",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3348",
      object_id: "column-3348",
      name: "QUESTION11",
      name_without_path: "QUESTION11",
      description: "Question11",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "240",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3349",
      object_id: "column-3349",
      name: "QUESTION12",
      name_without_path: "QUESTION12",
      description: "Question12",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "240",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
  ],
  relations: [],
  unique_keys: [
    {
      name: "PK_INCTYPEQUESTIONS",
      description: null,
      is_pk: true,
      is_user_defined: false,
      columns: [
        {
          path: null,
          name_without_path: "INCTYPE",
          name: "INCTYPE",
          column_id: 3336,
        },
      ],
      custom_fields: {},
    },
  ],
  triggers: [],
  dependencies: { uses: [], used_by: [] },
  object_id: "t152",
  name: "INCTYPEQUESTIONS",
  subtype: "TABLE",
  is_user_defined: false,
  description:
    '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\r\n                <html xmlns="http://www.w3.org/1999/xhtml">\r\n                    <head>\r\n                        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><title>\r\n                        </title>\r\n                        <style type="text/css">\r\n                            .cs2654AE3A{text-align:left;text-indent:0pt;margin:0pt 0pt 0pt 0pt}\r\n                            .cs416E45A4{color:#000000;background-color:transparent;font-family:\'Segoe UI\';font-size:10pt;font-weight:normal;font-style:normal;}\r\n                        </style>\r\n                    </head>\r\n                    <body>\r\n                        <p class="cs2654AE3A"><span class="cs416E45A4">INCTYPEQUESTIONS Information</span></p></body>\r\n                </html>',
  summary: [
    {
      field: "Documentation",
      value: { _type: "link", name: "SUN RIDGE SYSTEMS", id: "d1" },
    },
    { field: "Schema", value: "dbo" },
    { field: "Name", value: "INCTYPEQUESTIONS" },
    { field: "Type", value: "Table" },
  ],
  script: "",
  imported_at: "2024-10-01 02:34",
};
