window.repositoryObject = {
  columns_custom_fields: [],
  relations_custom_fields: [],
  unique_keys_custom_fields: [],
  triggers_custom_fields: [],
  columns: [
    {
      id: "column-3742",
      object_id: "column-3742",
      name: "ENTRYTYPE",
      name_without_path: "ENTRYTYPE",
      description: "Document release type",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "12",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3743",
      object_id: "column-3743",
      name: "DATERELEASED",
      name_without_path: "DATERELEASED",
      description: "Date Released",
      is_pk: false,
      is_identity: false,
      data_type: "datetime",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3744",
      object_id: "column-3744",
      name: "REASON",
      name_without_path: "REASON",
      description: "Reason",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "80",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3745",
      object_id: "column-3745",
      name: "NOTE",
      name_without_path: "NOTE",
      description: "Note",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "1000",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3746",
      object_id: "column-3746",
      name: "RELEASEDTO",
      name_without_path: "RELEASEDTO",
      description: "Released to",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "100",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3747",
      object_id: "column-3747",
      name: "ADDRESS",
      name_without_path: "ADDRESS",
      description: "Address",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "100",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3748",
      object_id: "column-3748",
      name: "PHONE",
      name_without_path: "PHONE",
      description: "Phone",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "20",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3749",
      object_id: "column-3749",
      name: "USERID",
      name_without_path: "USERID",
      description: "User ID",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "10",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [
        { id: "t385", name: "USERS", name_show_schema: "dbo.USERS" },
      ],
      linked_lookup: null,
    },
    {
      id: "column-3750",
      object_id: "column-3750",
      name: "CRTNUM",
      name_without_path: "CRTNUM",
      description: "CRT Num",
      is_pk: false,
      is_identity: false,
      data_type: "int",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [
        { id: "t30", name: "TERMINAL", name_show_schema: "dbo.TERMINAL" },
      ],
      linked_lookup: null,
    },
    {
      id: "column-3751",
      object_id: "column-3751",
      name: "AGCODE",
      name_without_path: "AGCODE",
      description: "Agency Code",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "6",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [
        { id: "t113", name: "AGENCY", name_show_schema: "dbo.AGENCY" },
      ],
      linked_lookup: null,
    },
    {
      id: "column-3752",
      object_id: "column-3752",
      name: "ITEMKEY",
      name_without_path: "ITEMKEY",
      description: "Item  Key",
      is_pk: false,
      is_identity: false,
      data_type: "int",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3753",
      object_id: "column-3753",
      name: "DATERUN",
      name_without_path: "DATERUN",
      description: "Date  Run",
      is_pk: false,
      is_identity: false,
      data_type: "datetime",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3754",
      object_id: "column-3754",
      name: "CASEN",
      name_without_path: "CASEN",
      description: "Case Number",
      is_pk: false,
      is_identity: false,
      data_type: "int",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [{ id: "t65", name: "CASES", name_show_schema: "dbo.CASES" }],
      linked_lookup: null,
    },
    {
      id: "column-3755",
      object_id: "column-3755",
      name: "FAKE_KEY",
      name_without_path: "FAKE_KEY",
      description: "Internal Key",
      is_pk: true,
      is_identity: true,
      data_type: "int",
      data_length: null,
      is_nullable: false,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
  ],
  relations: [
    {
      name: "FK_RELEASELOG_AGCODE",
      title: null,
      description: null,
      is_user_defined: false,
      foreign_table: "RELEASELOG",
      foreign_table_show_schema: "dbo.RELEASELOG",
      foreign_table_verbose: "RELEASELOG",
      foreign_table_verbose_show_schema: "dbo.RELEASELOG",
      foreign_table_object_id: "t172",
      primary_table: "AGENCY",
      primary_table_show_schema: "dbo.AGENCY",
      primary_table_verbose: "AGENCY",
      primary_table_verbose_show_schema: "dbo.AGENCY",
      primary_table_object_id: "t113",
      pk_cardinality: "1x",
      fk_cardinality: "mx",
      constraints: [
        {
          primary_column_path: null,
          primary_column: "AGCODE",
          foreign_column_path: null,
          foreign_column: "AGCODE",
        },
      ],
      custom_fields: {},
    },
    {
      name: "FK_RELEASELOG_CASES",
      title: null,
      description: null,
      is_user_defined: false,
      foreign_table: "RELEASELOG",
      foreign_table_show_schema: "dbo.RELEASELOG",
      foreign_table_verbose: "RELEASELOG",
      foreign_table_verbose_show_schema: "dbo.RELEASELOG",
      foreign_table_object_id: "t172",
      primary_table: "CASES",
      primary_table_show_schema: "dbo.CASES",
      primary_table_verbose: "CASES",
      primary_table_verbose_show_schema: "dbo.CASES",
      primary_table_object_id: "t65",
      pk_cardinality: "1x",
      fk_cardinality: "mx",
      constraints: [
        {
          primary_column_path: null,
          primary_column: "CASEN",
          foreign_column_path: null,
          foreign_column: "CASEN",
        },
      ],
      custom_fields: {},
    },
    {
      name: "FK_RELEASELOG_CRTNUM",
      title: null,
      description: null,
      is_user_defined: false,
      foreign_table: "RELEASELOG",
      foreign_table_show_schema: "dbo.RELEASELOG",
      foreign_table_verbose: "RELEASELOG",
      foreign_table_verbose_show_schema: "dbo.RELEASELOG",
      foreign_table_object_id: "t172",
      primary_table: "TERMINAL",
      primary_table_show_schema: "dbo.TERMINAL",
      primary_table_verbose: "TERMINAL",
      primary_table_verbose_show_schema: "dbo.TERMINAL",
      primary_table_object_id: "t30",
      pk_cardinality: "1x",
      fk_cardinality: "mx",
      constraints: [
        {
          primary_column_path: null,
          primary_column: "CRTNUM",
          foreign_column_path: null,
          foreign_column: "CRTNUM",
        },
      ],
      custom_fields: {},
    },
    {
      name: "FK_RELEASELOG_USERID",
      title: null,
      description: null,
      is_user_defined: false,
      foreign_table: "RELEASELOG",
      foreign_table_show_schema: "dbo.RELEASELOG",
      foreign_table_verbose: "RELEASELOG",
      foreign_table_verbose_show_schema: "dbo.RELEASELOG",
      foreign_table_object_id: "t172",
      primary_table: "USERS",
      primary_table_show_schema: "dbo.USERS",
      primary_table_verbose: "USERS",
      primary_table_verbose_show_schema: "dbo.USERS",
      primary_table_object_id: "t385",
      pk_cardinality: "1x",
      fk_cardinality: "mx",
      constraints: [
        {
          primary_column_path: null,
          primary_column: "USERID",
          foreign_column_path: null,
          foreign_column: "USERID",
        },
      ],
      custom_fields: {},
    },
  ],
  unique_keys: [
    {
      name: "PK_RELEASELOG",
      description: null,
      is_pk: true,
      is_user_defined: false,
      columns: [
        {
          path: null,
          name_without_path: "FAKE_KEY",
          name: "FAKE_KEY",
          column_id: 3755,
        },
      ],
      custom_fields: {},
    },
  ],
  triggers: [],
  dependencies: {
    uses: [
      {
        object_name: "RELEASELOG",
        object_name_show_schema: "dbo.RELEASELOG",
        object_type: "TABLE",
        object_id: "t172",
        type: "NORMAL",
        object_user_defined: false,
        user_defined: false,
        children: [
          {
            object_name: "AGENCY",
            object_name_show_schema: "dbo.AGENCY",
            object_type: "TABLE",
            object_id: "t113",
            type: "RELATION",
            pk_cardinality: "1x",
            fk_cardinality: "mx",
            object_user_defined: false,
            user_defined: false,
            children: [],
          },
          {
            object_name: "CASES",
            object_name_show_schema: "dbo.CASES",
            object_type: "TABLE",
            object_id: "t65",
            type: "RELATION",
            pk_cardinality: "1x",
            fk_cardinality: "mx",
            object_user_defined: false,
            user_defined: false,
            children: [],
          },
          {
            object_name: "TERMINAL",
            object_name_show_schema: "dbo.TERMINAL",
            object_type: "TABLE",
            object_id: "t30",
            type: "RELATION",
            pk_cardinality: "1x",
            fk_cardinality: "mx",
            object_user_defined: false,
            user_defined: false,
            children: [],
          },
          {
            object_name: "USERS",
            object_name_show_schema: "dbo.USERS",
            object_type: "TABLE",
            object_id: "t385",
            type: "RELATION",
            pk_cardinality: "1x",
            fk_cardinality: "mx",
            object_user_defined: false,
            user_defined: false,
            children: [],
          },
        ],
      },
    ],
    used_by: [],
  },
  object_id: "t172",
  name: "RELEASELOG",
  subtype: "TABLE",
  is_user_defined: false,
  description:
    '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\r\n                <html xmlns="http://www.w3.org/1999/xhtml">\r\n                    <head>\r\n                        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><title>\r\n                        </title>\r\n                        <style type="text/css">\r\n                            .cs2654AE3A{text-align:left;text-indent:0pt;margin:0pt 0pt 0pt 0pt}\r\n                            .cs416E45A4{color:#000000;background-color:transparent;font-family:\'Segoe UI\';font-size:10pt;font-weight:normal;font-style:normal;}\r\n                        </style>\r\n                    </head>\r\n                    <body>\r\n                        <p class="cs2654AE3A"><span class="cs416E45A4">Need a description</span></p></body>\r\n                </html>',
  summary: [
    {
      field: "Documentation",
      value: { _type: "link", name: "SUN RIDGE SYSTEMS", id: "d1" },
    },
    { field: "Schema", value: "dbo" },
    { field: "Name", value: "RELEASELOG" },
    { field: "Type", value: "Table" },
  ],
  script: "",
  imported_at: "2024-10-01 02:34",
};
