window.repositoryObject = {
  columns_custom_fields: [],
  relations_custom_fields: [],
  unique_keys_custom_fields: [],
  triggers_custom_fields: [],
  columns: [
    {
      id: "column-3785",
      object_id: "column-3785",
      name: "ID",
      name_without_path: "ID",
      description: "ID",
      is_pk: false,
      is_identity: false,
      data_type: "int",
      data_length: null,
      is_nullable: false,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [
        { id: "t412", name: "ALPHA", name_show_schema: "dbo.ALPHA" },
      ],
      linked_lookup: null,
    },
    {
      id: "column-3786",
      object_id: "column-3786",
      name: "NAME",
      name_without_path: "NAME",
      description: "Name",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "48",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3787",
      object_id: "column-3787",
      name: "ENTEREDBY",
      name_without_path: "ENTEREDBY",
      description: "Entered By",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "20",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3788",
      object_id: "column-3788",
      name: "DENIALNUM",
      name_without_path: "DENIALNUM",
      description: "Denial #",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "20",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3789",
      object_id: "column-3789",
      name: "BUSINESSREQUESTING",
      name_without_path: "BUSINESSREQUESTING",
      description: "Business Name",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "40",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3790",
      object_id: "column-3790",
      name: "PERSONREQUESTING",
      name_without_path: "PERSONREQUESTING",
      description: "Requested By",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "48",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3791",
      object_id: "column-3791",
      name: "ADDRESS",
      name_without_path: "ADDRESS",
      description: "Business Address",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "40",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3792",
      object_id: "column-3792",
      name: "SUITE",
      name_without_path: "SUITE",
      description: "Suite #",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "8",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3793",
      object_id: "column-3793",
      name: "CITY",
      name_without_path: "CITY",
      description: "Business City",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "30",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3794",
      object_id: "column-3794",
      name: "ST",
      name_without_path: "ST",
      description: "Business State",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "2",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3795",
      object_id: "column-3795",
      name: "REASON",
      name_without_path: "REASON",
      description: "Reason",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "2000",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3796",
      object_id: "column-3796",
      name: "DATEX",
      name_without_path: "DATEX",
      description: "Date",
      is_pk: false,
      is_identity: false,
      data_type: "datetime",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-3797",
      object_id: "column-3797",
      name: "AGCODE",
      name_without_path: "AGCODE",
      description: "Agency Code",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "6",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [
        { id: "t113", name: "AGENCY", name_show_schema: "dbo.AGENCY" },
      ],
      linked_lookup: null,
    },
    {
      id: "column-3798",
      object_id: "column-3798",
      name: "FAKE_KEY",
      name_without_path: "FAKE_KEY",
      description: "Internal Key",
      is_pk: true,
      is_identity: true,
      data_type: "int",
      data_length: null,
      is_nullable: false,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
  ],
  relations: [
    {
      name: "FK_FIREARMDENIAL_AGCODE",
      title: null,
      description: null,
      is_user_defined: false,
      foreign_table: "FIREARMDENIAL",
      foreign_table_show_schema: "dbo.FIREARMDENIAL",
      foreign_table_verbose: "FIREARMDENIAL",
      foreign_table_verbose_show_schema: "dbo.FIREARMDENIAL",
      foreign_table_object_id: "t174",
      primary_table: "AGENCY",
      primary_table_show_schema: "dbo.AGENCY",
      primary_table_verbose: "AGENCY",
      primary_table_verbose_show_schema: "dbo.AGENCY",
      primary_table_object_id: "t113",
      pk_cardinality: "1x",
      fk_cardinality: "mx",
      constraints: [
        {
          primary_column_path: null,
          primary_column: "AGCODE",
          foreign_column_path: null,
          foreign_column: "AGCODE",
        },
      ],
      custom_fields: {},
    },
    {
      name: "FK_FIREARMDENIAL_ID",
      title: null,
      description: null,
      is_user_defined: false,
      foreign_table: "FIREARMDENIAL",
      foreign_table_show_schema: "dbo.FIREARMDENIAL",
      foreign_table_verbose: "FIREARMDENIAL",
      foreign_table_verbose_show_schema: "dbo.FIREARMDENIAL",
      foreign_table_object_id: "t174",
      primary_table: "ALPHA",
      primary_table_show_schema: "dbo.ALPHA",
      primary_table_verbose: "ALPHA",
      primary_table_verbose_show_schema: "dbo.ALPHA",
      primary_table_object_id: "t412",
      pk_cardinality: "1x",
      fk_cardinality: "mx",
      constraints: [
        {
          primary_column_path: null,
          primary_column: "ID",
          foreign_column_path: null,
          foreign_column: "ID",
        },
      ],
      custom_fields: {},
    },
  ],
  unique_keys: [
    {
      name: "PK_FIREARMDENIAL",
      description: null,
      is_pk: true,
      is_user_defined: false,
      columns: [
        {
          path: null,
          name_without_path: "FAKE_KEY",
          name: "FAKE_KEY",
          column_id: 3798,
        },
      ],
      custom_fields: {},
    },
  ],
  triggers: [],
  dependencies: {
    uses: [
      {
        object_name: "FIREARMDENIAL",
        object_name_show_schema: "dbo.FIREARMDENIAL",
        object_type: "TABLE",
        object_id: "t174",
        type: "NORMAL",
        object_user_defined: false,
        user_defined: false,
        children: [
          {
            object_name: "AGENCY",
            object_name_show_schema: "dbo.AGENCY",
            object_type: "TABLE",
            object_id: "t113",
            type: "RELATION",
            pk_cardinality: "1x",
            fk_cardinality: "mx",
            object_user_defined: false,
            user_defined: false,
            children: [],
          },
          {
            object_name: "ALPHA",
            object_name_show_schema: "dbo.ALPHA",
            object_type: "TABLE",
            object_id: "t412",
            type: "RELATION",
            pk_cardinality: "1x",
            fk_cardinality: "mx",
            object_user_defined: false,
            user_defined: false,
            children: [],
          },
        ],
      },
    ],
    used_by: [],
  },
  object_id: "t174",
  name: "FIREARMDENIAL",
  subtype: "TABLE",
  is_user_defined: false,
  description:
    '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\r\n                <html xmlns="http://www.w3.org/1999/xhtml">\r\n                    <head>\r\n                        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><title>\r\n                        </title>\r\n                        <style type="text/css">\r\n                            .cs2654AE3A{text-align:left;text-indent:0pt;margin:0pt 0pt 0pt 0pt}\r\n                            .cs416E45A4{color:#000000;background-color:transparent;font-family:\'Segoe UI\';font-size:10pt;font-weight:normal;font-style:normal;}\r\n                        </style>\r\n                    </head>\r\n                    <body>\r\n                        <p class="cs2654AE3A"><span class="cs416E45A4">Need a description</span></p></body>\r\n                </html>',
  summary: [
    {
      field: "Documentation",
      value: { _type: "link", name: "SUN RIDGE SYSTEMS", id: "d1" },
    },
    { field: "Schema", value: "dbo" },
    { field: "Name", value: "FIREARMDENIAL" },
    { field: "Type", value: "Table" },
  ],
  script: "",
  imported_at: "2024-10-01 02:34",
};
