window.repositoryObject = {
  columns_custom_fields: [],
  relations_custom_fields: [],
  unique_keys_custom_fields: [],
  triggers_custom_fields: [],
  columns: [
    {
      id: "column-12",
      object_id: "column-12",
      name: "NAME",
      name_without_path: "NAME",
      description: "Name",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "40",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-13",
      object_id: "column-13",
      name: "CODE",
      name_without_path: "CODE",
      description: "Code",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "2",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-14",
      object_id: "column-14",
      name: "POPULATION",
      name_without_path: "POPULATION",
      description: "Population",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "7",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-15",
      object_id: "column-15",
      name: "TYPE",
      name_without_path: "TYPE",
      description: "Type",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "5",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-16",
      object_id: "column-16",
      name: "ADRS",
      name_without_path: "ADRS",
      description: null,
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "30",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-17",
      object_id: "column-17",
      name: "CITY",
      name_without_path: "CITY",
      description: "City",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "16",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-18",
      object_id: "column-18",
      name: "STATE",
      name_without_path: "STATE",
      description: "State",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "2",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-19",
      object_id: "column-19",
      name: "ZIP",
      name_without_path: "ZIP",
      description: "Zip",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "10",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-20",
      object_id: "column-20",
      name: "PHONE",
      name_without_path: "PHONE",
      description: "Phone",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "12",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-21",
      object_id: "column-21",
      name: "NOCELLMAINT",
      name_without_path: "NOCELLMAINT",
      description: null,
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "1",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-22",
      object_id: "column-22",
      name: "SSARPTID",
      name_without_path: "SSARPTID",
      description: "SSARPT ID",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "4",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-23",
      object_id: "column-23",
      name: "SSAFACID",
      name_without_path: "SSAFACID",
      description: "SSAFAC ID",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "6",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-24",
      object_id: "column-24",
      name: "FAKE_KEY",
      name_without_path: "FAKE_KEY",
      description: "Internal Key",
      is_pk: true,
      is_identity: true,
      data_type: "int",
      data_length: null,
      is_nullable: false,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-25",
      object_id: "column-25",
      name: "MULTIFACILITY",
      name_without_path: "MULTIFACILITY",
      description: "Multi  Facility",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "1",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-26",
      object_id: "column-26",
      name: "SRSSERVICEIP",
      name_without_path: "SRSSERVICEIP",
      description: "SRS Service IP",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "20",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-27",
      object_id: "column-27",
      name: "SRSSERVICEPort",
      name_without_path: "SRSSERVICEPort",
      description: "SRS Service  Port",
      is_pk: false,
      is_identity: false,
      data_type: "int",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-28",
      object_id: "column-28",
      name: "ARAMARKURL",
      name_without_path: "ARAMARKURL",
      description: "ARAMARK URL",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "255",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-29",
      object_id: "column-29",
      name: "ARAMARKUSERID",
      name_without_path: "ARAMARKUSERID",
      description: "ARAMARK User ID",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "25",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-30",
      object_id: "column-30",
      name: "ARAMARKPASSWORD",
      name_without_path: "ARAMARKPASSWORD",
      description: "ARAMARK Password",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "25",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-31",
      object_id: "column-31",
      name: "TELMATEURL",
      name_without_path: "TELMATEURL",
      description: "Tel MATE URL",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "255",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-32",
      object_id: "column-32",
      name: "TELMATEUSERID",
      name_without_path: "TELMATEUSERID",
      description: "Tel MATE User ID",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "25",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-33",
      object_id: "column-33",
      name: "TELMATEPASSWORD",
      name_without_path: "TELMATEPASSWORD",
      description: "Tel MATE Password",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "25",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-34",
      object_id: "column-34",
      name: "AGCODE",
      name_without_path: "AGCODE",
      description: "Agency Code",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "6",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [
        { id: "t113", name: "AGENCY", name_show_schema: "dbo.AGENCY" },
      ],
      linked_lookup: null,
    },
    {
      id: "column-35",
      object_id: "column-35",
      name: "JAILMAILUSERID1",
      name_without_path: "JAILMAILUSERID1",
      description: "Jail  Mail  User ID 1",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "10",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-36",
      object_id: "column-36",
      name: "JAILMAILUSERID2",
      name_without_path: "JAILMAILUSERID2",
      description: "Jail  Mail  User ID 2",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "10",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-37",
      object_id: "column-37",
      name: "NEXT_INVOICE",
      name_without_path: "NEXT_INVOICE",
      description: "Next  INVOICE",
      is_pk: false,
      is_identity: false,
      data_type: "int",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-38",
      object_id: "column-38",
      name: "BILLING_CONTACT",
      name_without_path: "BILLING_CONTACT",
      description: "Bill ING  Contact",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "10",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-39",
      object_id: "column-39",
      name: "USEINCAPPROVAL",
      name_without_path: "USEINCAPPROVAL",
      description: "Use INC App ROVAL",
      is_pk: false,
      is_identity: false,
      data_type: "char",
      data_length: "1",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-40",
      object_id: "column-40",
      name: "USECLERKREVIEW",
      name_without_path: "USECLERKREVIEW",
      description: "Use  Clerk  Re View",
      is_pk: false,
      is_identity: false,
      data_type: "char",
      data_length: "1",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-41",
      object_id: "column-41",
      name: "BODYCAMERARECORDINGREQ",
      name_without_path: "BODYCAMERARECORDINGREQ",
      description: "Body  Camera  Recording REQ",
      is_pk: false,
      is_identity: false,
      data_type: "char",
      data_length: "1",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-42",
      object_id: "column-42",
      name: "CREATEATTACHMENTREVIEWCOMPLETE",
      name_without_path: "CREATEATTACHMENTREVIEWCOMPLETE",
      description: "CREATE  Attachment  Re View   Complete",
      is_pk: false,
      is_identity: false,
      data_type: "char",
      data_length: "1",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-43",
      object_id: "column-43",
      name: "LATEINC",
      name_without_path: "LATEINC",
      description: null,
      is_pk: false,
      is_identity: false,
      data_type: "int",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-44",
      object_id: "column-44",
      name: "CASEITEMSPURGE",
      name_without_path: "CASEITEMSPURGE",
      description: "Case  Items Purge",
      is_pk: false,
      is_identity: false,
      data_type: "int",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-45",
      object_id: "column-45",
      name: "VISITHOLDDAYS",
      name_without_path: "VISITHOLDDAYS",
      description: "Visit Hold Days",
      is_pk: false,
      is_identity: false,
      data_type: "int",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-46",
      object_id: "column-46",
      name: "FACILITYORI",
      name_without_path: "FACILITYORI",
      description: "Facility ORI",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "9",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-47",
      object_id: "column-47",
      name: "PROPLOCFLAG",
      name_without_path: "PROPLOCFLAG",
      description: null,
      is_pk: false,
      is_identity: false,
      data_type: "char",
      data_length: "1",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-48",
      object_id: "column-48",
      name: "COURTUPDATE",
      name_without_path: "COURTUPDATE",
      description: "Next Court Date Update",
      is_pk: false,
      is_identity: false,
      data_type: "datetime",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-49",
      object_id: "column-49",
      name: "AUTOCOURTUPDATE",
      name_without_path: "AUTOCOURTUPDATE",
      description: "Update Next Court Date Daily",
      is_pk: false,
      is_identity: false,
      data_type: "char",
      data_length: "1",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-50",
      object_id: "column-50",
      name: "SRSSERVICEIPPORT",
      name_without_path: "SRSSERVICEIPPORT",
      description: null,
      is_pk: false,
      is_identity: false,
      data_type: "int",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
  ],
  relations: [
    {
      name: "FK_INM_FACILITY_AGCODE",
      title: null,
      description: null,
      is_user_defined: false,
      foreign_table: "INM_FACILITY",
      foreign_table_show_schema: "dbo.INM_FACILITY",
      foreign_table_verbose: "INM_FACILITY",
      foreign_table_verbose_show_schema: "dbo.INM_FACILITY",
      foreign_table_object_id: "t2",
      primary_table: "AGENCY",
      primary_table_show_schema: "dbo.AGENCY",
      primary_table_verbose: "AGENCY",
      primary_table_verbose_show_schema: "dbo.AGENCY",
      primary_table_object_id: "t113",
      pk_cardinality: "1x",
      fk_cardinality: "mx",
      constraints: [
        {
          primary_column_path: null,
          primary_column: "AGCODE",
          foreign_column_path: null,
          foreign_column: "AGCODE",
        },
      ],
      custom_fields: {},
    },
    {
      name: "FK_INM_BUILDING_FACILITY",
      title: null,
      description: null,
      is_user_defined: false,
      foreign_table: "INM_BUILDING",
      foreign_table_show_schema: "dbo.INM_BUILDING",
      foreign_table_verbose: "INM_BUILDING",
      foreign_table_verbose_show_schema: "dbo.INM_BUILDING",
      foreign_table_object_id: "t61",
      primary_table: "INM_FACILITY",
      primary_table_show_schema: "dbo.INM_FACILITY",
      primary_table_verbose: "INM_FACILITY",
      primary_table_verbose_show_schema: "dbo.INM_FACILITY",
      primary_table_object_id: "t2",
      pk_cardinality: "1x",
      fk_cardinality: "mx",
      constraints: [
        {
          primary_column_path: null,
          primary_column: "CODE",
          foreign_column_path: null,
          foreign_column: "FACILITY",
        },
      ],
      custom_fields: {},
    },
    {
      name: "FK_INM_CELLS_FACILITY",
      title: null,
      description: null,
      is_user_defined: false,
      foreign_table: "INM_CELLS",
      foreign_table_show_schema: "dbo.INM_CELLS",
      foreign_table_verbose: "INM_CELLS",
      foreign_table_verbose_show_schema: "dbo.INM_CELLS",
      foreign_table_object_id: "t56",
      primary_table: "INM_FACILITY",
      primary_table_show_schema: "dbo.INM_FACILITY",
      primary_table_verbose: "INM_FACILITY",
      primary_table_verbose_show_schema: "dbo.INM_FACILITY",
      primary_table_object_id: "t2",
      pk_cardinality: "1x",
      fk_cardinality: "mx",
      constraints: [
        {
          primary_column_path: null,
          primary_column: "CODE",
          foreign_column_path: null,
          foreign_column: "FACILITY",
        },
      ],
      custom_fields: {},
    },
  ],
  unique_keys: [
    {
      name: "PK_INM_FACILITY",
      description: null,
      is_pk: true,
      is_user_defined: false,
      columns: [
        {
          path: null,
          name_without_path: "FAKE_KEY",
          name: "FAKE_KEY",
          column_id: 24,
        },
      ],
      custom_fields: {},
    },
    {
      name: "INM_FACILITY_CODE",
      description: null,
      is_pk: false,
      is_user_defined: false,
      columns: [
        { path: null, name_without_path: "CODE", name: "CODE", column_id: 13 },
      ],
      custom_fields: {},
    },
  ],
  triggers: [],
  dependencies: {
    uses: [
      {
        object_name: "INM_FACILITY",
        object_name_show_schema: "dbo.INM_FACILITY",
        object_type: "TABLE",
        object_id: "t2",
        type: "NORMAL",
        object_user_defined: false,
        user_defined: false,
        children: [
          {
            object_name: "AGENCY",
            object_name_show_schema: "dbo.AGENCY",
            object_type: "TABLE",
            object_id: "t113",
            type: "RELATION",
            pk_cardinality: "1x",
            fk_cardinality: "mx",
            object_user_defined: false,
            user_defined: false,
            children: [],
          },
        ],
      },
    ],
    used_by: [
      {
        object_name: "INM_FACILITY",
        object_name_show_schema: "dbo.INM_FACILITY",
        object_type: "TABLE",
        object_id: "t2",
        type: "NORMAL",
        object_user_defined: false,
        user_defined: false,
        children: [
          {
            object_name: "INM_BUILDING",
            object_name_show_schema: "dbo.INM_BUILDING",
            object_type: "TABLE",
            object_id: "t61",
            type: "RELATION",
            pk_cardinality: "1x",
            fk_cardinality: "mx",
            object_user_defined: false,
            user_defined: false,
            children: [],
          },
          {
            object_name: "INM_CELLS",
            object_name_show_schema: "dbo.INM_CELLS",
            object_type: "TABLE",
            object_id: "t56",
            type: "RELATION",
            pk_cardinality: "1x",
            fk_cardinality: "mx",
            object_user_defined: false,
            user_defined: false,
            children: [],
          },
        ],
      },
    ],
  },
  object_id: "t2",
  name: "INM_FACILITY",
  subtype: "TABLE",
  is_user_defined: false,
  description:
    '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\r\n                <html xmlns="http://www.w3.org/1999/xhtml">\r\n                    <head>\r\n                        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><title>\r\n                        </title>\r\n                        <style type="text/css">\r\n                            .cs2654AE3A{text-align:left;text-indent:0pt;margin:0pt 0pt 0pt 0pt}\r\n                            .cs416E45A4{color:#000000;background-color:transparent;font-family:\'Segoe UI\';font-size:10pt;font-weight:normal;font-style:normal;}\r\n                        </style>\r\n                    </head>\r\n                    <body>\r\n                        <p class="cs2654AE3A"><span class="cs416E45A4">Facilities Using This Server</span></p></body>\r\n                </html>',
  summary: [
    {
      field: "Documentation",
      value: { _type: "link", name: "SUN RIDGE SYSTEMS", id: "d1" },
    },
    { field: "Schema", value: "dbo" },
    { field: "Name", value: "INM_FACILITY" },
    { field: "Type", value: "Table" },
  ],
  script: "",
  imported_at: "2024-10-01 02:34",
};
