window.repositoryObject = {
  columns_custom_fields: [],
  relations_custom_fields: [],
  unique_keys_custom_fields: [],
  triggers_custom_fields: [],
  columns: [
    {
      id: "column-5224",
      object_id: "column-5224",
      name: "INCNUM",
      name_without_path: "INCNUM",
      description: "INC Num",
      is_pk: false,
      is_identity: false,
      data_type: "int",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-5225",
      object_id: "column-5225",
      name: "BOOK_NO",
      name_without_path: "BOOK_NO",
      description: "Booking Number",
      is_pk: false,
      is_identity: false,
      data_type: "int",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [
        { id: "t69", name: "INM_BOOKING", name_show_schema: "dbo.INM_BOOKING" },
      ],
      linked_lookup: null,
    },
    {
      id: "column-5226",
      object_id: "column-5226",
      name: "DATEX",
      name_without_path: "DATEX",
      description: "Date X",
      is_pk: false,
      is_identity: false,
      data_type: "datetime",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-5227",
      object_id: "column-5227",
      name: "TIMEX",
      name_without_path: "TIMEX",
      description: "Time X",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "5",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-5228",
      object_id: "column-5228",
      name: "HEAROFCR1",
      name_without_path: "HEAROFCR1",
      description: "Hear Officer1",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "10",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-5229",
      object_id: "column-5229",
      name: "HEAROFCR2",
      name_without_path: "HEAROFCR2",
      description: "Hear Officer2",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "10",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-5230",
      object_id: "column-5230",
      name: "HEAROFCR3",
      name_without_path: "HEAROFCR3",
      description: "Hear Officer3",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "10",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-5231",
      object_id: "column-5231",
      name: "NOTES",
      name_without_path: "NOTES",
      description: "Note S",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "500",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-5232",
      object_id: "column-5232",
      name: "DETERMINATION",
      name_without_path: "DETERMINATION",
      description: "De Termination",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "500",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-5233",
      object_id: "column-5233",
      name: "HEARINGRIGHTSGIVEN",
      name_without_path: "HEARINGRIGHTSGIVEN",
      description: "Hearing Rights Given",
      is_pk: false,
      is_identity: false,
      data_type: "char",
      data_length: "1",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-5234",
      object_id: "column-5234",
      name: "FAKE_KEY",
      name_without_path: "FAKE_KEY",
      description: "Internal Key",
      is_pk: true,
      is_identity: true,
      data_type: "int",
      data_length: null,
      is_nullable: false,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-5235",
      object_id: "column-5235",
      name: "INM_DISCIPLINARY_HEARINGS",
      name_without_path: "INM_DISCIPLINARY_HEARINGS",
      description: "INM  Disc IPLINARY  Hear INGS",
      is_pk: false,
      is_identity: false,
      data_type: "int",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-5236",
      object_id: "column-5236",
      name: "LOCATION",
      name_without_path: "LOCATION",
      description: "Location",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "30",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-5237",
      object_id: "column-5237",
      name: "DISPO",
      name_without_path: "DISPO",
      description: null,
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "4",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-5238",
      object_id: "column-5238",
      name: "DISCIPLINARYKEY",
      name_without_path: "DISCIPLINARYKEY",
      description: null,
      is_pk: false,
      is_identity: false,
      data_type: "int",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
  ],
  relations: [
    {
      name: "FK_INM_DISCIPLINARY_HEARINGS_BOOKNO",
      title: null,
      description: null,
      is_user_defined: false,
      foreign_table: "INM_DISCIPLINARY_HEARINGS",
      foreign_table_show_schema: "dbo.INM_DISCIPLINARY_HEARINGS",
      foreign_table_verbose: "INM_DISCIPLINARY_HEARINGS",
      foreign_table_verbose_show_schema: "dbo.INM_DISCIPLINARY_HEARINGS",
      foreign_table_object_id: "t233",
      primary_table: "INM_BOOKING",
      primary_table_show_schema: "dbo.INM_BOOKING",
      primary_table_verbose: "INM_BOOKING",
      primary_table_verbose_show_schema: "dbo.INM_BOOKING",
      primary_table_object_id: "t69",
      pk_cardinality: "1x",
      fk_cardinality: "mx",
      constraints: [
        {
          primary_column_path: null,
          primary_column: "BOOKNO",
          foreign_column_path: null,
          foreign_column: "BOOK_NO",
        },
      ],
      custom_fields: {},
    },
  ],
  unique_keys: [
    {
      name: "PK_INM_DISCIPLINARY_HEARINGS",
      description: null,
      is_pk: true,
      is_user_defined: false,
      columns: [
        {
          path: null,
          name_without_path: "FAKE_KEY",
          name: "FAKE_KEY",
          column_id: 5234,
        },
      ],
      custom_fields: {},
    },
  ],
  triggers: [],
  dependencies: {
    uses: [
      {
        object_name: "INM_DISCIPLINARY_HEARINGS",
        object_name_show_schema: "dbo.INM_DISCIPLINARY_HEARINGS",
        object_type: "TABLE",
        object_id: "t233",
        type: "NORMAL",
        object_user_defined: false,
        user_defined: false,
        children: [
          {
            object_name: "INM_BOOKING",
            object_name_show_schema: "dbo.INM_BOOKING",
            object_type: "TABLE",
            object_id: "t69",
            type: "RELATION",
            pk_cardinality: "1x",
            fk_cardinality: "mx",
            object_user_defined: false,
            user_defined: false,
            children: [],
          },
        ],
      },
    ],
    used_by: [],
  },
  object_id: "t233",
  name: "INM_DISCIPLINARY_HEARINGS",
  subtype: "TABLE",
  is_user_defined: false,
  description:
    '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\r\n                <html xmlns="http://www.w3.org/1999/xhtml">\r\n                    <head>\r\n                        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><title>\r\n                        </title>\r\n                        <style type="text/css">\r\n                            .cs2654AE3A{text-align:left;text-indent:0pt;margin:0pt 0pt 0pt 0pt}\r\n                            .cs416E45A4{color:#000000;background-color:transparent;font-family:\'Segoe UI\';font-size:10pt;font-weight:normal;font-style:normal;}\r\n                        </style>\r\n                    </head>\r\n                    <body>\r\n                        <p class="cs2654AE3A"><span class="cs416E45A4">Need a description</span></p></body>\r\n                </html>',
  summary: [
    {
      field: "Documentation",
      value: { _type: "link", name: "SUN RIDGE SYSTEMS", id: "d1" },
    },
    { field: "Schema", value: "dbo" },
    { field: "Name", value: "INM_DISCIPLINARY_HEARINGS" },
    { field: "Type", value: "Table" },
  ],
  script: "",
  imported_at: "2024-10-01 02:34",
};
