window.repositoryObject = {
  columns_custom_fields: [],
  relations_custom_fields: [],
  unique_keys_custom_fields: [],
  triggers_custom_fields: [],
  columns: [
    {
      id: "column-8441",
      object_id: "column-8441",
      name: "CITATION",
      name_without_path: "CITATION",
      description: "Citation",
      is_pk: true,
      is_identity: false,
      data_type: "varchar",
      data_length: "20",
      is_nullable: false,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8442",
      object_id: "column-8442",
      name: "CITETYPE",
      name_without_path: "CITETYPE",
      description: "Citation Type",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "1",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8443",
      object_id: "column-8443",
      name: "DATEX",
      name_without_path: "DATEX",
      description: "Date Issued",
      is_pk: false,
      is_identity: false,
      data_type: "datetime",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8444",
      object_id: "column-8444",
      name: "VIO1",
      name_without_path: "VIO1",
      description: "Citation Classification",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "32",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8445",
      object_id: "column-8445",
      name: "VIO2",
      name_without_path: "VIO2",
      description: "Citation Classification",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "32",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8446",
      object_id: "column-8446",
      name: "VIO3",
      name_without_path: "VIO3",
      description: "Citation Classification",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "32",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8447",
      object_id: "column-8447",
      name: "VIO4",
      name_without_path: "VIO4",
      description: "Citation Classification",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "32",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8448",
      object_id: "column-8448",
      name: "ID",
      name_without_path: "ID",
      description: "ID",
      is_pk: false,
      is_identity: false,
      data_type: "int",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8449",
      object_id: "column-8449",
      name: "LOCATION",
      name_without_path: "LOCATION",
      description: "Location",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "48",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8450",
      object_id: "column-8450",
      name: "GRID",
      name_without_path: "GRID",
      description: "Grid",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "6",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8451",
      object_id: "column-8451",
      name: "SRA",
      name_without_path: "SRA",
      description: "Reporting Areas",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "6",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8452",
      object_id: "column-8452",
      name: "ODATE",
      name_without_path: "ODATE",
      description: "Date Occurred",
      is_pk: false,
      is_identity: false,
      data_type: "datetime",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8453",
      object_id: "column-8453",
      name: "OTIM",
      name_without_path: "OTIM",
      description: "Time Occurred",
      is_pk: false,
      is_identity: false,
      data_type: "int",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8454",
      object_id: "column-8454",
      name: "ODAY",
      name_without_path: "ODAY",
      description: "O Day",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "2",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8455",
      object_id: "column-8455",
      name: "LICENSE",
      name_without_path: "LICENSE",
      description: "License",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "12",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8456",
      object_id: "column-8456",
      name: "ST",
      name_without_path: "ST",
      description: "License State",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "2",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8457",
      object_id: "column-8457",
      name: "OFF1",
      name_without_path: "OFF1",
      description: "Citation Dispositions",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "20",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8458",
      object_id: "column-8458",
      name: "BADGE1",
      name_without_path: "BADGE1",
      description: "Vehicle Searched",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "6",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8459",
      object_id: "column-8459",
      name: "OFF2",
      name_without_path: "OFF2",
      description: null,
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "20",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8460",
      object_id: "column-8460",
      name: "BADGE2",
      name_without_path: "BADGE2",
      description: "Badge 2",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "6",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8461",
      object_id: "column-8461",
      name: "OFF_APP",
      name_without_path: "OFF_APP",
      description: "OFF  App",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "20",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8462",
      object_id: "column-8462",
      name: "BADGE3",
      name_without_path: "BADGE3",
      description: "Badge 3",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "6",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8463",
      object_id: "column-8463",
      name: "D_APP",
      name_without_path: "D_APP",
      description: "D  App",
      is_pk: false,
      is_identity: false,
      data_type: "datetime",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8464",
      object_id: "column-8464",
      name: "T_APP",
      name_without_path: "T_APP",
      description: "T  App",
      is_pk: false,
      is_identity: false,
      data_type: "int",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8465",
      object_id: "column-8465",
      name: "ROUTETO",
      name_without_path: "ROUTETO",
      description: "Route To",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "20",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8466",
      object_id: "column-8466",
      name: "RTDATE",
      name_without_path: "RTDATE",
      description: "Route Date",
      is_pk: false,
      is_identity: false,
      data_type: "datetime",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8467",
      object_id: "column-8467",
      name: "DOCKET",
      name_without_path: "DOCKET",
      description: "Docket",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "8",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8468",
      object_id: "column-8468",
      name: "FINE1",
      name_without_path: "FINE1",
      description: "Fine 1",
      is_pk: false,
      is_identity: false,
      data_type: "float",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8469",
      object_id: "column-8469",
      name: "FINE2",
      name_without_path: "FINE2",
      description: "Fine 2",
      is_pk: false,
      is_identity: false,
      data_type: "float",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8470",
      object_id: "column-8470",
      name: "FINE3",
      name_without_path: "FINE3",
      description: "Fine 3",
      is_pk: false,
      is_identity: false,
      data_type: "float",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8471",
      object_id: "column-8471",
      name: "DESC1",
      name_without_path: "DESC1",
      description: "Violation Desc",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "120",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8472",
      object_id: "column-8472",
      name: "DESC2",
      name_without_path: "DESC2",
      description: "Violation Desc 2",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "120",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8473",
      object_id: "column-8473",
      name: "DESC3",
      name_without_path: "DESC3",
      description: "Violation Desc 3",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "120",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8474",
      object_id: "column-8474",
      name: "RC1",
      name_without_path: "RC1",
      description: "Violation Type",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "1",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8475",
      object_id: "column-8475",
      name: "RC2",
      name_without_path: "RC2",
      description: "Violation Type 2",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "1",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8476",
      object_id: "column-8476",
      name: "RC3",
      name_without_path: "RC3",
      description: "Violation Type 3",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "1",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8477",
      object_id: "column-8477",
      name: "CITESTAT",
      name_without_path: "CITESTAT",
      description: "Citation Status",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "1",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8478",
      object_id: "column-8478",
      name: "RECEIPT",
      name_without_path: "RECEIPT",
      description: "Receipt",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "7",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8479",
      object_id: "column-8479",
      name: "DATEPAID",
      name_without_path: "DATEPAID",
      description: "Date Paid",
      is_pk: false,
      is_identity: false,
      data_type: "datetime",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8480",
      object_id: "column-8480",
      name: "AMTPAID",
      name_without_path: "AMTPAID",
      description: "Amount Paid",
      is_pk: false,
      is_identity: false,
      data_type: "float",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8481",
      object_id: "column-8481",
      name: "COURTDATE",
      name_without_path: "COURTDATE",
      description: "Court Date",
      is_pk: false,
      is_identity: false,
      data_type: "datetime",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8482",
      object_id: "column-8482",
      name: "WARNDATE",
      name_without_path: "WARNDATE",
      description: "Warning Ltr Date",
      is_pk: false,
      is_identity: false,
      data_type: "datetime",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8483",
      object_id: "column-8483",
      name: "DMVDATE",
      name_without_path: "DMVDATE",
      description: "DMV Sent Date",
      is_pk: false,
      is_identity: false,
      data_type: "datetime",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8484",
      object_id: "column-8484",
      name: "DISPDATE",
      name_without_path: "DISPDATE",
      description: "Disposition Date",
      is_pk: false,
      is_identity: false,
      data_type: "datetime",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8485",
      object_id: "column-8485",
      name: "SUBNAME",
      name_without_path: "SUBNAME",
      description: "SUB Name",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "48",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8486",
      object_id: "column-8486",
      name: "SUBADRS",
      name_without_path: "SUBADRS",
      description: null,
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "40",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8487",
      object_id: "column-8487",
      name: "SUBCITY",
      name_without_path: "SUBCITY",
      description: "SUB City",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "24",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8488",
      object_id: "column-8488",
      name: "SUBSTATE",
      name_without_path: "SUBSTATE",
      description: "SUB State",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "2",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8489",
      object_id: "column-8489",
      name: "SUBZIP",
      name_without_path: "SUBZIP",
      description: "SUB Zip",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "7",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8490",
      object_id: "column-8490",
      name: "VEHDESC",
      name_without_path: "VEHDESC",
      description: null,
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "50",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8491",
      object_id: "column-8491",
      name: "AMTDUE",
      name_without_path: "AMTDUE",
      description: "Amount Due",
      is_pk: false,
      is_identity: false,
      data_type: "float",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8492",
      object_id: "column-8492",
      name: "BALDUE",
      name_without_path: "BALDUE",
      description: "Balance Due",
      is_pk: false,
      is_identity: false,
      data_type: "float",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8493",
      object_id: "column-8493",
      name: "VEHTYPE",
      name_without_path: "VEHTYPE",
      description: "Citation Vehicle Type",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "1",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8494",
      object_id: "column-8494",
      name: "BIKEID",
      name_without_path: "BIKEID",
      description: "Bike  ID",
      is_pk: false,
      is_identity: false,
      data_type: "int",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8495",
      object_id: "column-8495",
      name: "LASTUPDATE",
      name_without_path: "LASTUPDATE",
      description: "Last Update",
      is_pk: false,
      is_identity: false,
      data_type: "datetime",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8496",
      object_id: "column-8496",
      name: "CITY",
      name_without_path: "CITY",
      description: "City",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "8",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8497",
      object_id: "column-8497",
      name: "RC4",
      name_without_path: "RC4",
      description: "Violation Type 4",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "1",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8498",
      object_id: "column-8498",
      name: "DESC4",
      name_without_path: "DESC4",
      description: "Violation Desc 4",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "120",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8499",
      object_id: "column-8499",
      name: "FINE4",
      name_without_path: "FINE4",
      description: "Fine 4",
      is_pk: false,
      is_identity: false,
      data_type: "float",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8500",
      object_id: "column-8500",
      name: "BEAT",
      name_without_path: "BEAT",
      description: "Beat",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "6",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8501",
      object_id: "column-8501",
      name: "OFCRNUM1",
      name_without_path: "OFCRNUM1",
      description: "Officer",
      is_pk: false,
      is_identity: false,
      data_type: "int",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8502",
      object_id: "column-8502",
      name: "OFCRNUM2",
      name_without_path: "OFCRNUM2",
      description: "Officer",
      is_pk: false,
      is_identity: false,
      data_type: "int",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8503",
      object_id: "column-8503",
      name: "OFCRNUMAPP",
      name_without_path: "OFCRNUMAPP",
      description: "Officer",
      is_pk: false,
      is_identity: false,
      data_type: "int",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8504",
      object_id: "column-8504",
      name: "OPID",
      name_without_path: "OPID",
      description: "OP ID",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "10",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8505",
      object_id: "column-8505",
      name: "VEHICLEID",
      name_without_path: "VEHICLEID",
      description: "Vehicle ID",
      is_pk: false,
      is_identity: false,
      data_type: "int",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [
        { id: "t88", name: "VEHICLE", name_show_schema: "dbo.VEHICLE" },
      ],
      linked_lookup: null,
    },
    {
      id: "column-8506",
      object_id: "column-8506",
      name: "NARRATIVE",
      name_without_path: "NARRATIVE",
      description: null,
      is_pk: false,
      is_identity: false,
      data_type: "text",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8507",
      object_id: "column-8507",
      name: "PLACE",
      name_without_path: "PLACE",
      description: "Place",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "40",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8508",
      object_id: "column-8508",
      name: "NOTE",
      name_without_path: "NOTE",
      description: "Note",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "70",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8509",
      object_id: "column-8509",
      name: "INCNUM",
      name_without_path: "INCNUM",
      description: "Incident #",
      is_pk: false,
      is_identity: false,
      data_type: "bigint",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [
        { id: "t347", name: "INCIDENT", name_show_schema: "dbo.INCIDENT" },
      ],
      linked_lookup: null,
    },
    {
      id: "column-8510",
      object_id: "column-8510",
      name: "USERID",
      name_without_path: "USERID",
      description: "User ID",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "10",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [
        { id: "t385", name: "USERS", name_show_schema: "dbo.USERS" },
      ],
      linked_lookup: null,
    },
    {
      id: "column-8511",
      object_id: "column-8511",
      name: "STUDENT",
      name_without_path: "STUDENT",
      description: "Student",
      is_pk: false,
      is_identity: false,
      data_type: "char",
      data_length: "1",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8512",
      object_id: "column-8512",
      name: "OWNERID",
      name_without_path: "OWNERID",
      description: "Own ER ID",
      is_pk: false,
      is_identity: false,
      data_type: "int",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [
        { id: "t412", name: "ALPHA", name_show_schema: "dbo.ALPHA" },
      ],
      linked_lookup: null,
    },
    {
      id: "column-8513",
      object_id: "column-8513",
      name: "SUBAPT",
      name_without_path: "SUBAPT",
      description: null,
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "8",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8514",
      object_id: "column-8514",
      name: "DRIVERISRO",
      name_without_path: "DRIVERISRO",
      description: "Driver is RO",
      is_pk: false,
      is_identity: false,
      data_type: "char",
      data_length: "1",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8515",
      object_id: "column-8515",
      name: "RADARCITE",
      name_without_path: "RADARCITE",
      description: "Radar Cite",
      is_pk: false,
      is_identity: false,
      data_type: "char",
      data_length: "1",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8516",
      object_id: "column-8516",
      name: "COURTDISPODATE",
      name_without_path: "COURTDISPODATE",
      description: "Court Dispo Date",
      is_pk: false,
      is_identity: false,
      data_type: "datetime",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8517",
      object_id: "column-8517",
      name: "COURTDISPO",
      name_without_path: "COURTDISPO",
      description: "Citation Court Disposition",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "10",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8518",
      object_id: "column-8518",
      name: "COURTTIME",
      name_without_path: "COURTTIME",
      description: "Court Time",
      is_pk: false,
      is_identity: false,
      data_type: "int",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8519",
      object_id: "column-8519",
      name: "VIO5",
      name_without_path: "VIO5",
      description: "Citation Classification",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "32",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8520",
      object_id: "column-8520",
      name: "VIO6",
      name_without_path: "VIO6",
      description: "Violation 6",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "32",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8521",
      object_id: "column-8521",
      name: "DESC5",
      name_without_path: "DESC5",
      description: "Violation Desc 5",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "120",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8522",
      object_id: "column-8522",
      name: "DESC6",
      name_without_path: "DESC6",
      description: "Violation Desc 6",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "120",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8523",
      object_id: "column-8523",
      name: "RC5",
      name_without_path: "RC5",
      description: "Violation Type 5",
      is_pk: false,
      is_identity: false,
      data_type: "char",
      data_length: "1",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8524",
      object_id: "column-8524",
      name: "RC6",
      name_without_path: "RC6",
      description: "Violation Type 6",
      is_pk: false,
      is_identity: false,
      data_type: "char",
      data_length: "1",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8525",
      object_id: "column-8525",
      name: "FINE5",
      name_without_path: "FINE5",
      description: "Fine 5",
      is_pk: false,
      is_identity: false,
      data_type: "float",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8526",
      object_id: "column-8526",
      name: "FINE6",
      name_without_path: "FINE6",
      description: "Fine 6",
      is_pk: false,
      is_identity: false,
      data_type: "float",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8527",
      object_id: "column-8527",
      name: "CASEN",
      name_without_path: "CASEN",
      description: "Case #",
      is_pk: false,
      is_identity: false,
      data_type: "int",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [{ id: "t65", name: "CASES", name_show_schema: "dbo.CASES" }],
      linked_lookup: null,
    },
    {
      id: "column-8528",
      object_id: "column-8528",
      name: "DATEENTERED",
      name_without_path: "DATEENTERED",
      description: "Date Entered",
      is_pk: false,
      is_identity: false,
      data_type: "datetime",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8529",
      object_id: "column-8529",
      name: "LIDAR",
      name_without_path: "LIDAR",
      description: "Lidar",
      is_pk: false,
      is_identity: false,
      data_type: "char",
      data_length: "1",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8530",
      object_id: "column-8530",
      name: "XCOORD",
      name_without_path: "XCOORD",
      description: "X-Coordinate",
      is_pk: false,
      is_identity: false,
      data_type: "float",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8531",
      object_id: "column-8531",
      name: "YCOORD",
      name_without_path: "YCOORD",
      description: "Y-Coordinate",
      is_pk: false,
      is_identity: false,
      data_type: "float",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8532",
      object_id: "column-8532",
      name: "COORDCHECK",
      name_without_path: "COORDCHECK",
      description: "COORD Check",
      is_pk: false,
      is_identity: false,
      data_type: "char",
      data_length: "1",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8533",
      object_id: "column-8533",
      name: "COURT",
      name_without_path: "COURT",
      description: "Judicial District",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "10",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8534",
      object_id: "column-8534",
      name: "GEOLOCATION",
      name_without_path: "GEOLOCATION",
      description: "Geocoded Location",
      is_pk: false,
      is_identity: false,
      data_type: "image",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8535",
      object_id: "column-8535",
      name: "SEARCHEDVEHICLE",
      name_without_path: "SEARCHEDVEHICLE",
      description: "Searched Vehicle",
      is_pk: false,
      is_identity: false,
      data_type: "char",
      data_length: "1",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-8536",
      object_id: "column-8536",
      name: "NOTICEOFCORRECTION",
      name_without_path: "NOTICEOFCORRECTION",
      description: "Notice of Correction",
      is_pk: false,
      is_identity: false,
      data_type: "char",
      data_length: "1",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
  ],
  relations: [
    {
      name: "FK_CITATION_OWNERID",
      title: null,
      description: null,
      is_user_defined: false,
      foreign_table: "CITATION",
      foreign_table_show_schema: "dbo.CITATION",
      foreign_table_verbose: "CITATION",
      foreign_table_verbose_show_schema: "dbo.CITATION",
      foreign_table_object_id: "t357",
      primary_table: "ALPHA",
      primary_table_show_schema: "dbo.ALPHA",
      primary_table_verbose: "ALPHA",
      primary_table_verbose_show_schema: "dbo.ALPHA",
      primary_table_object_id: "t412",
      pk_cardinality: "1x",
      fk_cardinality: "mx",
      constraints: [
        {
          primary_column_path: null,
          primary_column: "ID",
          foreign_column_path: null,
          foreign_column: "OWNERID",
        },
      ],
      custom_fields: {},
    },
    {
      name: "FK_CITATION_CASES",
      title: null,
      description: null,
      is_user_defined: false,
      foreign_table: "CITATION",
      foreign_table_show_schema: "dbo.CITATION",
      foreign_table_verbose: "CITATION",
      foreign_table_verbose_show_schema: "dbo.CITATION",
      foreign_table_object_id: "t357",
      primary_table: "CASES",
      primary_table_show_schema: "dbo.CASES",
      primary_table_verbose: "CASES",
      primary_table_verbose_show_schema: "dbo.CASES",
      primary_table_object_id: "t65",
      pk_cardinality: "1x",
      fk_cardinality: "mx",
      constraints: [
        {
          primary_column_path: null,
          primary_column: "CASEN",
          foreign_column_path: null,
          foreign_column: "CASEN",
        },
      ],
      custom_fields: {},
    },
    {
      name: "FK_CITATION_INCNUM",
      title: null,
      description: null,
      is_user_defined: false,
      foreign_table: "CITATION",
      foreign_table_show_schema: "dbo.CITATION",
      foreign_table_verbose: "CITATION",
      foreign_table_verbose_show_schema: "dbo.CITATION",
      foreign_table_object_id: "t357",
      primary_table: "INCIDENT",
      primary_table_show_schema: "dbo.INCIDENT",
      primary_table_verbose: "INCIDENT",
      primary_table_verbose_show_schema: "dbo.INCIDENT",
      primary_table_object_id: "t347",
      pk_cardinality: "1x",
      fk_cardinality: "mx",
      constraints: [
        {
          primary_column_path: null,
          primary_column: "INCNUM",
          foreign_column_path: null,
          foreign_column: "INCNUM",
        },
      ],
      custom_fields: {},
    },
    {
      name: "FK_CITATION_USERID",
      title: null,
      description: null,
      is_user_defined: false,
      foreign_table: "CITATION",
      foreign_table_show_schema: "dbo.CITATION",
      foreign_table_verbose: "CITATION",
      foreign_table_verbose_show_schema: "dbo.CITATION",
      foreign_table_object_id: "t357",
      primary_table: "USERS",
      primary_table_show_schema: "dbo.USERS",
      primary_table_verbose: "USERS",
      primary_table_verbose_show_schema: "dbo.USERS",
      primary_table_object_id: "t385",
      pk_cardinality: "1x",
      fk_cardinality: "mx",
      constraints: [
        {
          primary_column_path: null,
          primary_column: "USERID",
          foreign_column_path: null,
          foreign_column: "USERID",
        },
      ],
      custom_fields: {},
    },
    {
      name: "FK_CITATION_VEHICLEID",
      title: null,
      description: null,
      is_user_defined: false,
      foreign_table: "CITATION",
      foreign_table_show_schema: "dbo.CITATION",
      foreign_table_verbose: "CITATION",
      foreign_table_verbose_show_schema: "dbo.CITATION",
      foreign_table_object_id: "t357",
      primary_table: "VEHICLE",
      primary_table_show_schema: "dbo.VEHICLE",
      primary_table_verbose: "VEHICLE",
      primary_table_verbose_show_schema: "dbo.VEHICLE",
      primary_table_object_id: "t88",
      pk_cardinality: "1x",
      fk_cardinality: "mx",
      constraints: [
        {
          primary_column_path: null,
          primary_column: "VEHICLEID",
          foreign_column_path: null,
          foreign_column: "VEHICLEID",
        },
      ],
      custom_fields: {},
    },
    {
      name: "FK_AINFO_CITATION",
      title: null,
      description: null,
      is_user_defined: false,
      foreign_table: "AINFO",
      foreign_table_show_schema: "dbo.AINFO",
      foreign_table_verbose: "AINFO",
      foreign_table_verbose_show_schema: "dbo.AINFO",
      foreign_table_object_id: "t380",
      primary_table: "CITATION",
      primary_table_show_schema: "dbo.CITATION",
      primary_table_verbose: "CITATION",
      primary_table_verbose_show_schema: "dbo.CITATION",
      primary_table_object_id: "t357",
      pk_cardinality: "1x",
      fk_cardinality: "mx",
      constraints: [
        {
          primary_column_path: null,
          primary_column: "CITATION",
          foreign_column_path: null,
          foreign_column: "CITATION",
        },
      ],
      custom_fields: {},
    },
    {
      name: "FK_BIKEHIST_CITATION",
      title: null,
      description: null,
      is_user_defined: false,
      foreign_table: "BIKEHIST",
      foreign_table_show_schema: "dbo.BIKEHIST",
      foreign_table_verbose: "BIKEHIST",
      foreign_table_verbose_show_schema: "dbo.BIKEHIST",
      foreign_table_object_id: "t388",
      primary_table: "CITATION",
      primary_table_show_schema: "dbo.CITATION",
      primary_table_verbose: "CITATION",
      primary_table_verbose_show_schema: "dbo.CITATION",
      primary_table_object_id: "t357",
      pk_cardinality: "1x",
      fk_cardinality: "mx",
      constraints: [
        {
          primary_column_path: null,
          primary_column: "CITATION",
          foreign_column_path: null,
          foreign_column: "CITATION",
        },
      ],
      custom_fields: {},
    },
    {
      name: "FK_CASEPERS_CITATION",
      title: null,
      description: null,
      is_user_defined: false,
      foreign_table: "CASEPERS",
      foreign_table_show_schema: "dbo.CASEPERS",
      foreign_table_verbose: "CASEPERS",
      foreign_table_verbose_show_schema: "dbo.CASEPERS",
      foreign_table_object_id: "t248",
      primary_table: "CITATION",
      primary_table_show_schema: "dbo.CITATION",
      primary_table_verbose: "CITATION",
      primary_table_verbose_show_schema: "dbo.CITATION",
      primary_table_object_id: "t357",
      pk_cardinality: "1x",
      fk_cardinality: "mx",
      constraints: [
        {
          primary_column_path: null,
          primary_column: "CITATION",
          foreign_column_path: null,
          foreign_column: "CITATION",
        },
      ],
      custom_fields: {},
    },
    {
      name: "FK_CITEATTACH_CITATION",
      title: null,
      description: null,
      is_user_defined: false,
      foreign_table: "CITEATTACH",
      foreign_table_show_schema: "dbo.CITEATTACH",
      foreign_table_verbose: "CITEATTACH",
      foreign_table_verbose_show_schema: "dbo.CITEATTACH",
      foreign_table_object_id: "t329",
      primary_table: "CITATION",
      primary_table_show_schema: "dbo.CITATION",
      primary_table_verbose: "CITATION",
      primary_table_verbose_show_schema: "dbo.CITATION",
      primary_table_object_id: "t357",
      pk_cardinality: "1x",
      fk_cardinality: "mx",
      constraints: [
        {
          primary_column_path: null,
          primary_column: "CITATION",
          foreign_column_path: null,
          foreign_column: "CITATION",
        },
      ],
      custom_fields: {},
    },
    {
      name: "FK_CITEAUDIT_CITATION",
      title: null,
      description: null,
      is_user_defined: false,
      foreign_table: "CITEAUDIT",
      foreign_table_show_schema: "dbo.CITEAUDIT",
      foreign_table_verbose: "CITEAUDIT",
      foreign_table_verbose_show_schema: "dbo.CITEAUDIT",
      foreign_table_object_id: "t142",
      primary_table: "CITATION",
      primary_table_show_schema: "dbo.CITATION",
      primary_table_verbose: "CITATION",
      primary_table_verbose_show_schema: "dbo.CITATION",
      primary_table_object_id: "t357",
      pk_cardinality: "1x",
      fk_cardinality: "mx",
      constraints: [
        {
          primary_column_path: null,
          primary_column: "CITATION",
          foreign_column_path: null,
          foreign_column: "CITATION",
        },
      ],
      custom_fields: {},
    },
    {
      name: "FK_CITEPHOTOS_CITEKEY",
      title: null,
      description: null,
      is_user_defined: false,
      foreign_table: "CITEPHOTOS",
      foreign_table_show_schema: "dbo.CITEPHOTOS",
      foreign_table_verbose: "CITEPHOTOS",
      foreign_table_verbose_show_schema: "dbo.CITEPHOTOS",
      foreign_table_object_id: "t149",
      primary_table: "CITATION",
      primary_table_show_schema: "dbo.CITATION",
      primary_table_verbose: "CITATION",
      primary_table_verbose_show_schema: "dbo.CITATION",
      primary_table_object_id: "t357",
      pk_cardinality: "1x",
      fk_cardinality: "mx",
      constraints: [
        {
          primary_column_path: null,
          primary_column: "CITATION",
          foreign_column_path: null,
          foreign_column: "CITEKEY",
        },
      ],
      custom_fields: {},
    },
    {
      name: "FK_MAPDATA_CITATION",
      title: null,
      description: null,
      is_user_defined: false,
      foreign_table: "MAPDATA",
      foreign_table_show_schema: "dbo.MAPDATA",
      foreign_table_verbose: "MAPDATA",
      foreign_table_verbose_show_schema: "dbo.MAPDATA",
      foreign_table_object_id: "t273",
      primary_table: "CITATION",
      primary_table_show_schema: "dbo.CITATION",
      primary_table_verbose: "CITATION",
      primary_table_verbose_show_schema: "dbo.CITATION",
      primary_table_object_id: "t357",
      pk_cardinality: "1x",
      fk_cardinality: "mx",
      constraints: [
        {
          primary_column_path: null,
          primary_column: "CITATION",
          foreign_column_path: null,
          foreign_column: "CITATION",
        },
      ],
      custom_fields: {},
    },
    {
      name: "FK_MESSAGES_CITATION",
      title: null,
      description: null,
      is_user_defined: false,
      foreign_table: "MESSAGES",
      foreign_table_show_schema: "dbo.MESSAGES",
      foreign_table_verbose: "MESSAGES",
      foreign_table_verbose_show_schema: "dbo.MESSAGES",
      foreign_table_object_id: "t279",
      primary_table: "CITATION",
      primary_table_show_schema: "dbo.CITATION",
      primary_table_verbose: "CITATION",
      primary_table_verbose_show_schema: "dbo.CITATION",
      primary_table_object_id: "t357",
      pk_cardinality: "1x",
      fk_cardinality: "mx",
      constraints: [
        {
          primary_column_path: null,
          primary_column: "CITATION",
          foreign_column_path: null,
          foreign_column: "CITATION",
        },
      ],
      custom_fields: {},
    },
    {
      name: "FK_SUBPOENA_CITATION",
      title: null,
      description: null,
      is_user_defined: false,
      foreign_table: "SUBPOENA",
      foreign_table_show_schema: "dbo.SUBPOENA",
      foreign_table_verbose: "SUBPOENA",
      foreign_table_verbose_show_schema: "dbo.SUBPOENA",
      foreign_table_object_id: "t144",
      primary_table: "CITATION",
      primary_table_show_schema: "dbo.CITATION",
      primary_table_verbose: "CITATION",
      primary_table_verbose_show_schema: "dbo.CITATION",
      primary_table_object_id: "t357",
      pk_cardinality: "1x",
      fk_cardinality: "mx",
      constraints: [
        {
          primary_column_path: null,
          primary_column: "CITATION",
          foreign_column_path: null,
          foreign_column: "CITATION",
        },
      ],
      custom_fields: {},
    },
    {
      name: "FK_WARRANT_CITATION",
      title: null,
      description: null,
      is_user_defined: false,
      foreign_table: "WARRANT",
      foreign_table_show_schema: "dbo.WARRANT",
      foreign_table_verbose: "WARRANT",
      foreign_table_verbose_show_schema: "dbo.WARRANT",
      foreign_table_object_id: "t305",
      primary_table: "CITATION",
      primary_table_show_schema: "dbo.CITATION",
      primary_table_verbose: "CITATION",
      primary_table_verbose_show_schema: "dbo.CITATION",
      primary_table_object_id: "t357",
      pk_cardinality: "1x",
      fk_cardinality: "mx",
      constraints: [
        {
          primary_column_path: null,
          primary_column: "CITATION",
          foreign_column_path: null,
          foreign_column: "CITATION",
        },
      ],
      custom_fields: {},
    },
    {
      name: "FK_XMITALPH_CITATION",
      title: null,
      description: null,
      is_user_defined: false,
      foreign_table: "XMITALPH",
      foreign_table_show_schema: "dbo.XMITALPH",
      foreign_table_verbose: "XMITALPH",
      foreign_table_verbose_show_schema: "dbo.XMITALPH",
      foreign_table_object_id: "t311",
      primary_table: "CITATION",
      primary_table_show_schema: "dbo.CITATION",
      primary_table_verbose: "CITATION",
      primary_table_verbose_show_schema: "dbo.CITATION",
      primary_table_object_id: "t357",
      pk_cardinality: "1x",
      fk_cardinality: "mx",
      constraints: [
        {
          primary_column_path: null,
          primary_column: "CITATION",
          foreign_column_path: null,
          foreign_column: "CITATION",
        },
      ],
      custom_fields: {},
    },
  ],
  unique_keys: [
    {
      name: "PK_CITATION",
      description: null,
      is_pk: true,
      is_user_defined: false,
      columns: [
        {
          path: null,
          name_without_path: "CITATION",
          name: "CITATION",
          column_id: 8441,
        },
      ],
      custom_fields: {},
    },
  ],
  triggers: [],
  dependencies: {
    uses: [
      {
        object_name: "CITATION",
        object_name_show_schema: "dbo.CITATION",
        object_type: "TABLE",
        object_id: "t357",
        type: "NORMAL",
        object_user_defined: false,
        user_defined: false,
        children: [
          {
            object_name: "ALPHA",
            object_name_show_schema: "dbo.ALPHA",
            object_type: "TABLE",
            object_id: "t412",
            type: "RELATION",
            pk_cardinality: "1x",
            fk_cardinality: "mx",
            object_user_defined: false,
            user_defined: false,
            children: [],
          },
          {
            object_name: "CASES",
            object_name_show_schema: "dbo.CASES",
            object_type: "TABLE",
            object_id: "t65",
            type: "RELATION",
            pk_cardinality: "1x",
            fk_cardinality: "mx",
            object_user_defined: false,
            user_defined: false,
            children: [],
          },
          {
            object_name: "INCIDENT",
            object_name_show_schema: "dbo.INCIDENT",
            object_type: "TABLE",
            object_id: "t347",
            type: "RELATION",
            pk_cardinality: "1x",
            fk_cardinality: "mx",
            object_user_defined: false,
            user_defined: false,
            children: [],
          },
          {
            object_name: "USERS",
            object_name_show_schema: "dbo.USERS",
            object_type: "TABLE",
            object_id: "t385",
            type: "RELATION",
            pk_cardinality: "1x",
            fk_cardinality: "mx",
            object_user_defined: false,
            user_defined: false,
            children: [],
          },
          {
            object_name: "VEHICLE",
            object_name_show_schema: "dbo.VEHICLE",
            object_type: "TABLE",
            object_id: "t88",
            type: "RELATION",
            pk_cardinality: "1x",
            fk_cardinality: "mx",
            object_user_defined: false,
            user_defined: false,
            children: [],
          },
        ],
      },
    ],
    used_by: [
      {
        object_name: "CITATION",
        object_name_show_schema: "dbo.CITATION",
        object_type: "TABLE",
        object_id: "t357",
        type: "NORMAL",
        object_user_defined: false,
        user_defined: false,
        children: [
          {
            object_name: "AINFO",
            object_name_show_schema: "dbo.AINFO",
            object_type: "TABLE",
            object_id: "t380",
            type: "RELATION",
            pk_cardinality: "1x",
            fk_cardinality: "mx",
            object_user_defined: false,
            user_defined: false,
            children: [],
          },
          {
            object_name: "BIKEHIST",
            object_name_show_schema: "dbo.BIKEHIST",
            object_type: "TABLE",
            object_id: "t388",
            type: "RELATION",
            pk_cardinality: "1x",
            fk_cardinality: "mx",
            object_user_defined: false,
            user_defined: false,
            children: [],
          },
          {
            object_name: "CASEPERS",
            object_name_show_schema: "dbo.CASEPERS",
            object_type: "TABLE",
            object_id: "t248",
            type: "RELATION",
            pk_cardinality: "1x",
            fk_cardinality: "mx",
            object_user_defined: false,
            user_defined: false,
            children: [],
          },
          {
            object_name: "CITEATTACH",
            object_name_show_schema: "dbo.CITEATTACH",
            object_type: "TABLE",
            object_id: "t329",
            type: "RELATION",
            pk_cardinality: "1x",
            fk_cardinality: "mx",
            object_user_defined: false,
            user_defined: false,
            children: [],
          },
          {
            object_name: "CITEAUDIT",
            object_name_show_schema: "dbo.CITEAUDIT",
            object_type: "TABLE",
            object_id: "t142",
            type: "RELATION",
            pk_cardinality: "1x",
            fk_cardinality: "mx",
            object_user_defined: false,
            user_defined: false,
            children: [],
          },
          {
            object_name: "CITEPHOTOS",
            object_name_show_schema: "dbo.CITEPHOTOS",
            object_type: "TABLE",
            object_id: "t149",
            type: "RELATION",
            pk_cardinality: "1x",
            fk_cardinality: "mx",
            object_user_defined: false,
            user_defined: false,
            children: [],
          },
          {
            object_name: "MAPDATA",
            object_name_show_schema: "dbo.MAPDATA",
            object_type: "TABLE",
            object_id: "t273",
            type: "RELATION",
            pk_cardinality: "1x",
            fk_cardinality: "mx",
            object_user_defined: false,
            user_defined: false,
            children: [],
          },
          {
            object_name: "MESSAGES",
            object_name_show_schema: "dbo.MESSAGES",
            object_type: "TABLE",
            object_id: "t279",
            type: "RELATION",
            pk_cardinality: "1x",
            fk_cardinality: "mx",
            object_user_defined: false,
            user_defined: false,
            children: [],
          },
          {
            object_name: "SUBPOENA",
            object_name_show_schema: "dbo.SUBPOENA",
            object_type: "TABLE",
            object_id: "t144",
            type: "RELATION",
            pk_cardinality: "1x",
            fk_cardinality: "mx",
            object_user_defined: false,
            user_defined: false,
            children: [],
          },
          {
            object_name: "WARRANT",
            object_name_show_schema: "dbo.WARRANT",
            object_type: "TABLE",
            object_id: "t305",
            type: "RELATION",
            pk_cardinality: "1x",
            fk_cardinality: "mx",
            object_user_defined: false,
            user_defined: false,
            children: [],
          },
          {
            object_name: "XMITALPH",
            object_name_show_schema: "dbo.XMITALPH",
            object_type: "TABLE",
            object_id: "t311",
            type: "RELATION",
            pk_cardinality: "1x",
            fk_cardinality: "mx",
            object_user_defined: false,
            user_defined: false,
            children: [],
          },
        ],
      },
    ],
  },
  object_id: "t357",
  name: "CITATION",
  subtype: "TABLE",
  is_user_defined: false,
  description:
    '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\r\n                <html xmlns="http://www.w3.org/1999/xhtml">\r\n                    <head>\r\n                        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><title>\r\n                        </title>\r\n                        <style type="text/css">\r\n                            .cs2654AE3A{text-align:left;text-indent:0pt;margin:0pt 0pt 0pt 0pt}\r\n                            .cs416E45A4{color:#000000;background-color:transparent;font-family:\'Segoe UI\';font-size:10pt;font-weight:normal;font-style:normal;}\r\n                        </style>\r\n                    </head>\r\n                    <body>\r\n                        <p class="cs2654AE3A"><span class="cs416E45A4">Citations</span></p></body>\r\n                </html>',
  summary: [
    {
      field: "Documentation",
      value: { _type: "link", name: "SUN RIDGE SYSTEMS", id: "d1" },
    },
    { field: "Schema", value: "dbo" },
    { field: "Name", value: "CITATION" },
    { field: "Type", value: "Table" },
  ],
  script: "",
  imported_at: "2024-10-01 02:34",
};
