window.repositoryObject = {
  columns_custom_fields: [],
  relations_custom_fields: [],
  unique_keys_custom_fields: [],
  triggers_custom_fields: [],
  columns: [
    {
      id: "column-1223",
      object_id: "column-1223",
      name: "INCNUM",
      name_without_path: "INCNUM",
      description: "INC Num",
      is_pk: true,
      is_identity: false,
      data_type: "bigint",
      data_length: null,
      is_nullable: false,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [
        { id: "t347", name: "INCIDENT", name_show_schema: "dbo.INCIDENT" },
      ],
      linked_lookup: null,
    },
    {
      id: "column-1224",
      object_id: "column-1224",
      name: "USERID",
      name_without_path: "USERID",
      description: "User ID",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "10",
      is_nullable: false,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [
        { id: "t385", name: "USERS", name_show_schema: "dbo.USERS" },
      ],
      linked_lookup: null,
    },
    {
      id: "column-1225",
      object_id: "column-1225",
      name: "DATEX",
      name_without_path: "DATEX",
      description: "Date X",
      is_pk: false,
      is_identity: false,
      data_type: "datetime",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1226",
      object_id: "column-1226",
      name: "TIMEX",
      name_without_path: "TIMEX",
      description: "Time X",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "8",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1227",
      object_id: "column-1227",
      name: "INCTYPE",
      name_without_path: "INCTYPE",
      description: "INC Type",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "8",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1228",
      object_id: "column-1228",
      name: "NOTE",
      name_without_path: "NOTE",
      description: "Note",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "240",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1229",
      object_id: "column-1229",
      name: "QUESTION1",
      name_without_path: "QUESTION1",
      description: "Question1",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "240",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1230",
      object_id: "column-1230",
      name: "ANSWER1",
      name_without_path: "ANSWER1",
      description: "Answer 1",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "400",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1231",
      object_id: "column-1231",
      name: "QUESTION2",
      name_without_path: "QUESTION2",
      description: "Question2",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "240",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1232",
      object_id: "column-1232",
      name: "ANSWER2",
      name_without_path: "ANSWER2",
      description: "Answer 2",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "400",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1233",
      object_id: "column-1233",
      name: "QUESTION3",
      name_without_path: "QUESTION3",
      description: "Question3",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "240",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1234",
      object_id: "column-1234",
      name: "ANSWER3",
      name_without_path: "ANSWER3",
      description: "Answer 3",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "400",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1235",
      object_id: "column-1235",
      name: "QUESTION4",
      name_without_path: "QUESTION4",
      description: "Question4",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "240",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1236",
      object_id: "column-1236",
      name: "ANSWER4",
      name_without_path: "ANSWER4",
      description: "Answer 4",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "400",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1237",
      object_id: "column-1237",
      name: "QUESTION5",
      name_without_path: "QUESTION5",
      description: "Question5",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "240",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1238",
      object_id: "column-1238",
      name: "ANSWER5",
      name_without_path: "ANSWER5",
      description: "Answer 5",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "400",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1239",
      object_id: "column-1239",
      name: "QUESTION6",
      name_without_path: "QUESTION6",
      description: "Question6",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "240",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1240",
      object_id: "column-1240",
      name: "ANSWER6",
      name_without_path: "ANSWER6",
      description: "Answer 6",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "400",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1241",
      object_id: "column-1241",
      name: "QUESTION7",
      name_without_path: "QUESTION7",
      description: "Question7",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "240",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1242",
      object_id: "column-1242",
      name: "ANSWER7",
      name_without_path: "ANSWER7",
      description: "Answer 7",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "400",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1243",
      object_id: "column-1243",
      name: "QUESTION8",
      name_without_path: "QUESTION8",
      description: "Question8",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "240",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1244",
      object_id: "column-1244",
      name: "ANSWER8",
      name_without_path: "ANSWER8",
      description: "Answer 8",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "400",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1245",
      object_id: "column-1245",
      name: "QUESTION9",
      name_without_path: "QUESTION9",
      description: "Question9",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "240",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1246",
      object_id: "column-1246",
      name: "ANSWER9",
      name_without_path: "ANSWER9",
      description: "Answer 9",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "400",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1247",
      object_id: "column-1247",
      name: "QUESTION10",
      name_without_path: "QUESTION10",
      description: "Question10",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "240",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1248",
      object_id: "column-1248",
      name: "ANSWER10",
      name_without_path: "ANSWER10",
      description: "Answer 10",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "400",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1249",
      object_id: "column-1249",
      name: "QUESTION11",
      name_without_path: "QUESTION11",
      description: "Question11",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "240",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1250",
      object_id: "column-1250",
      name: "ANSWER11",
      name_without_path: "ANSWER11",
      description: "Answer 11",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "400",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1251",
      object_id: "column-1251",
      name: "QUESTION12",
      name_without_path: "QUESTION12",
      description: "Question12",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "240",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1252",
      object_id: "column-1252",
      name: "ANSWER12",
      name_without_path: "ANSWER12",
      description: "Answer 12",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "400",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
  ],
  relations: [
    {
      name: "FK_INCQUESTIONS_INCNUM",
      title: null,
      description: null,
      is_user_defined: false,
      foreign_table: "INCQUESTIONS",
      foreign_table_show_schema: "dbo.INCQUESTIONS",
      foreign_table_verbose: "INCQUESTIONS",
      foreign_table_verbose_show_schema: "dbo.INCQUESTIONS",
      foreign_table_object_id: "t57",
      primary_table: "INCIDENT",
      primary_table_show_schema: "dbo.INCIDENT",
      primary_table_verbose: "INCIDENT",
      primary_table_verbose_show_schema: "dbo.INCIDENT",
      primary_table_object_id: "t347",
      pk_cardinality: "1x",
      fk_cardinality: "mx",
      constraints: [
        {
          primary_column_path: null,
          primary_column: "INCNUM",
          foreign_column_path: null,
          foreign_column: "INCNUM",
        },
      ],
      custom_fields: {},
    },
    {
      name: "FK_INCQUESTIONS_USERID",
      title: null,
      description: null,
      is_user_defined: false,
      foreign_table: "INCQUESTIONS",
      foreign_table_show_schema: "dbo.INCQUESTIONS",
      foreign_table_verbose: "INCQUESTIONS",
      foreign_table_verbose_show_schema: "dbo.INCQUESTIONS",
      foreign_table_object_id: "t57",
      primary_table: "USERS",
      primary_table_show_schema: "dbo.USERS",
      primary_table_verbose: "USERS",
      primary_table_verbose_show_schema: "dbo.USERS",
      primary_table_object_id: "t385",
      pk_cardinality: "1x",
      fk_cardinality: "mx",
      constraints: [
        {
          primary_column_path: null,
          primary_column: "USERID",
          foreign_column_path: null,
          foreign_column: "USERID",
        },
      ],
      custom_fields: {},
    },
  ],
  unique_keys: [
    {
      name: "PK_INCQUESTIONS",
      description: null,
      is_pk: true,
      is_user_defined: false,
      columns: [
        {
          path: null,
          name_without_path: "INCNUM",
          name: "INCNUM",
          column_id: 1223,
        },
      ],
      custom_fields: {},
    },
  ],
  triggers: [],
  dependencies: {
    uses: [
      {
        object_name: "INCQUESTIONS",
        object_name_show_schema: "dbo.INCQUESTIONS",
        object_type: "TABLE",
        object_id: "t57",
        type: "NORMAL",
        object_user_defined: false,
        user_defined: false,
        children: [
          {
            object_name: "INCIDENT",
            object_name_show_schema: "dbo.INCIDENT",
            object_type: "TABLE",
            object_id: "t347",
            type: "RELATION",
            pk_cardinality: "1x",
            fk_cardinality: "mx",
            object_user_defined: false,
            user_defined: false,
            children: [],
          },
          {
            object_name: "USERS",
            object_name_show_schema: "dbo.USERS",
            object_type: "TABLE",
            object_id: "t385",
            type: "RELATION",
            pk_cardinality: "1x",
            fk_cardinality: "mx",
            object_user_defined: false,
            user_defined: false,
            children: [],
          },
        ],
      },
    ],
    used_by: [],
  },
  object_id: "t57",
  name: "INCQUESTIONS",
  subtype: "TABLE",
  is_user_defined: false,
  description:
    '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\r\n                <html xmlns="http://www.w3.org/1999/xhtml">\r\n                    <head>\r\n                        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><title>\r\n                        </title>\r\n                        <style type="text/css">\r\n                            .cs2654AE3A{text-align:left;text-indent:0pt;margin:0pt 0pt 0pt 0pt}\r\n                            .cs416E45A4{color:#000000;background-color:transparent;font-family:\'Segoe UI\';font-size:10pt;font-weight:normal;font-style:normal;}\r\n                        </style>\r\n                    </head>\r\n                    <body>\r\n                        <p class="cs2654AE3A"><span class="cs416E45A4">Need a description</span></p></body>\r\n                </html>',
  summary: [
    {
      field: "Documentation",
      value: { _type: "link", name: "SUN RIDGE SYSTEMS", id: "d1" },
    },
    { field: "Schema", value: "dbo" },
    { field: "Name", value: "INCQUESTIONS" },
    { field: "Type", value: "Table" },
  ],
  script: "",
  imported_at: "2024-10-01 02:34",
};
