window.repositoryObject = {
  columns_custom_fields: [],
  relations_custom_fields: [],
  unique_keys_custom_fields: [],
  triggers_custom_fields: [],
  columns: [
    {
      id: "column-1594",
      object_id: "column-1594",
      name: "BOOKNO",
      name_without_path: "BOOKNO",
      description: "Booking Number",
      is_pk: true,
      is_identity: false,
      data_type: "int",
      data_length: null,
      is_nullable: false,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1595",
      object_id: "column-1595",
      name: "ALPHAID",
      name_without_path: "ALPHAID",
      description: "Person ID",
      is_pk: false,
      is_identity: false,
      data_type: "int",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [
        { id: "t412", name: "ALPHA", name_show_schema: "dbo.ALPHA" },
      ],
      linked_lookup: null,
    },
    {
      id: "column-1596",
      object_id: "column-1596",
      name: "BOOKDATE",
      name_without_path: "BOOKDATE",
      description: "Booking Date",
      is_pk: false,
      is_identity: false,
      data_type: "datetime",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1597",
      object_id: "column-1597",
      name: "BOOKTIME",
      name_without_path: "BOOKTIME",
      description: "Booking Time",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "5",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1598",
      object_id: "column-1598",
      name: "OCANO",
      name_without_path: "OCANO",
      description: "Case#",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "20",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1599",
      object_id: "column-1599",
      name: "CITENO",
      name_without_path: "CITENO",
      description: "Cite No",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "10",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1600",
      object_id: "column-1600",
      name: "CRIMERPTNO",
      name_without_path: "CRIMERPTNO",
      description: "Crime Report Number",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "10",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1601",
      object_id: "column-1601",
      name: "AGNWARRNO",
      name_without_path: "AGNWARRNO",
      description: "Agency Warrant Numbr",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "10",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1602",
      object_id: "column-1602",
      name: "BOOKEVENT",
      name_without_path: "BOOKEVENT",
      description: "Event (Jail Module)",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "2",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1603",
      object_id: "column-1603",
      name: "BOOKAGENCY",
      name_without_path: "BOOKAGENCY",
      description: "Booking Agency",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "30",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1604",
      object_id: "column-1604",
      name: "ARSTTYPE",
      name_without_path: "ARSTTYPE",
      description: "Arrest Type (Jail Module)",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "2",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1605",
      object_id: "column-1605",
      name: "ARSTAGENCY",
      name_without_path: "ARSTAGENCY",
      description: "Arresting Agency",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "30",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1606",
      object_id: "column-1606",
      name: "ARSTDATE",
      name_without_path: "ARSTDATE",
      description: "Arrest Date",
      is_pk: false,
      is_identity: false,
      data_type: "datetime",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1607",
      object_id: "column-1607",
      name: "ARSTLOC",
      name_without_path: "ARSTLOC",
      description: "Arrest Location",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "30",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1608",
      object_id: "column-1608",
      name: "ARSTAREA",
      name_without_path: "ARSTAREA",
      description: "Arrest Area",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "10",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1609",
      object_id: "column-1609",
      name: "OFFNLOC",
      name_without_path: "OFFNLOC",
      description: "Offense Location",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "30",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1610",
      object_id: "column-1610",
      name: "OFFNAREA",
      name_without_path: "OFFNAREA",
      description: "Offense Area",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "10",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1611",
      object_id: "column-1611",
      name: "AROF1",
      name_without_path: "AROF1",
      description: "Arresting Officer 1",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "10",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1612",
      object_id: "column-1612",
      name: "AROF2",
      name_without_path: "AROF2",
      description: "Arresting Officer 2",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "10",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1613",
      object_id: "column-1613",
      name: "TPOF1",
      name_without_path: "TPOF1",
      description: "Transport Officer 1",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "10",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1614",
      object_id: "column-1614",
      name: "TPOF2",
      name_without_path: "TPOF2",
      description: "Transport Officer 1",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "10",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1615",
      object_id: "column-1615",
      name: "STAYLENGTH",
      name_without_path: "STAYLENGTH",
      description: "Length of Jail Stay",
      is_pk: false,
      is_identity: false,
      data_type: "int",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1616",
      object_id: "column-1616",
      name: "SPECNOTE",
      name_without_path: "SPECNOTE",
      description: "Special Comments",
      is_pk: false,
      is_identity: false,
      data_type: "text",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1617",
      object_id: "column-1617",
      name: "RELEASED",
      name_without_path: "RELEASED",
      description: "Released",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "1",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1618",
      object_id: "column-1618",
      name: "OUTDATE",
      name_without_path: "OUTDATE",
      description: "Schedule Release",
      is_pk: false,
      is_identity: false,
      data_type: "datetime",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1619",
      object_id: "column-1619",
      name: "OUTTIME",
      name_without_path: "OUTTIME",
      description: "OUT Time",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "5",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1620",
      object_id: "column-1620",
      name: "OUTCOMMENTS",
      name_without_path: "OUTCOMMENTS",
      description: "Out Comments",
      is_pk: false,
      is_identity: false,
      data_type: "image",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1621",
      object_id: "column-1621",
      name: "OUTREASON",
      name_without_path: "OUTREASON",
      description: "Release Inmate Reason (Jail Module)",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "4",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1622",
      object_id: "column-1622",
      name: "OUTTRANSFER",
      name_without_path: "OUTTRANSFER",
      description: "Out Transferred",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "1",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1623",
      object_id: "column-1623",
      name: "OUTOFFICER",
      name_without_path: "OUTOFFICER",
      description: "Out Officer",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "10",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1624",
      object_id: "column-1624",
      name: "RELPOSTDATE",
      name_without_path: "RELPOSTDATE",
      description: "REL Post  Date",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "25",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1625",
      object_id: "column-1625",
      name: "FACILITY",
      name_without_path: "FACILITY",
      description: "Facility",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "2",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1626",
      object_id: "column-1626",
      name: "BUILDING",
      name_without_path: "BUILDING",
      description: "Building",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "2",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1627",
      object_id: "column-1627",
      name: "FLOOR",
      name_without_path: "FLOOR",
      description: "Floor",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "4",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1628",
      object_id: "column-1628",
      name: "SECTION",
      name_without_path: "SECTION",
      description: "Section",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "4",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1629",
      object_id: "column-1629",
      name: "CELL",
      name_without_path: "CELL",
      description: "Cell",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "4",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1630",
      object_id: "column-1630",
      name: "SUBCELL",
      name_without_path: "SUBCELL",
      description: "Sub Cell",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "4",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1631",
      object_id: "column-1631",
      name: "CLASSIFICATION",
      name_without_path: "CLASSIFICATION",
      description: "Booking Classification (Jail Module)",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "3",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1632",
      object_id: "column-1632",
      name: "BOOKTYPE",
      name_without_path: "BOOKTYPE",
      description: "Booking Type (Jail Module)",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "1",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1633",
      object_id: "column-1633",
      name: "STATUS",
      name_without_path: "STATUS",
      description: "Status (Jail Module)",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "2",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1634",
      object_id: "column-1634",
      name: "PICKUPDATE",
      name_without_path: "PICKUPDATE",
      description: "PickUpdate",
      is_pk: false,
      is_identity: false,
      data_type: "datetime",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1635",
      object_id: "column-1635",
      name: "PICKUPTIME",
      name_without_path: "PICKUPTIME",
      description: "Pickup Time",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "5",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1636",
      object_id: "column-1636",
      name: "ARSTTIME",
      name_without_path: "ARSTTIME",
      description: "ARST Time",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "5",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1637",
      object_id: "column-1637",
      name: "COMBALANCE",
      name_without_path: "COMBALANCE",
      description: "Balance",
      is_pk: false,
      is_identity: false,
      data_type: "numeric",
      data_length: "18, 2",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1638",
      object_id: "column-1638",
      name: "BOOF1",
      name_without_path: "BOOF1",
      description: "Booking Officer 1",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "20",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1639",
      object_id: "column-1639",
      name: "BOOF2",
      name_without_path: "BOOF2",
      description: "Booking Officer 2",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "20",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1640",
      object_id: "column-1640",
      name: "RECVOF1",
      name_without_path: "RECVOF1",
      description: "Receiving Officer 1",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "20",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1641",
      object_id: "column-1641",
      name: "RECVOF2",
      name_without_path: "RECVOF2",
      description: "Receiving Officer 2",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "20",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1642",
      object_id: "column-1642",
      name: "SEAROF1",
      name_without_path: "SEAROF1",
      description: "Searching Officer 1",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "20",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1643",
      object_id: "column-1643",
      name: "SEAROF2",
      name_without_path: "SEAROF2",
      description: "Searching Officer 2",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "20",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1644",
      object_id: "column-1644",
      name: "SUSPCOMMISSARY",
      name_without_path: "SUSPCOMMISSARY",
      description: "Suspend Commissary",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "1",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1645",
      object_id: "column-1645",
      name: "BOOKINGCOMPLETE",
      name_without_path: "BOOKINGCOMPLETE",
      description: "Booking Complete",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "1",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1646",
      object_id: "column-1646",
      name: "BOOKPOSTDATE",
      name_without_path: "BOOKPOSTDATE",
      description: "Book  Post  Date",
      is_pk: false,
      is_identity: false,
      data_type: "datetime",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1647",
      object_id: "column-1647",
      name: "RELEASEPOSTDATE",
      name_without_path: "RELEASEPOSTDATE",
      description: "Release  Post  Date",
      is_pk: false,
      is_identity: false,
      data_type: "datetime",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1648",
      object_id: "column-1648",
      name: "SENTAFIS",
      name_without_path: "SENTAFIS",
      description: "AFIS?",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "1",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1649",
      object_id: "column-1649",
      name: "PARENT_BOOKNO",
      name_without_path: "PARENT_BOOKNO",
      description: "Parent   Book NO",
      is_pk: false,
      is_identity: false,
      data_type: "int",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1650",
      object_id: "column-1650",
      name: "OUTFACILITY",
      name_without_path: "OUTFACILITY",
      description: "Out of Facility Reason (Jail Module)",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "1",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1651",
      object_id: "column-1651",
      name: "OUTFACILITYDATEOUT",
      name_without_path: "OUTFACILITYDATEOUT",
      description: "OUT Facility  Date OUT",
      is_pk: false,
      is_identity: false,
      data_type: "datetime",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1652",
      object_id: "column-1652",
      name: "OUTFACILITYTIMEOUT",
      name_without_path: "OUTFACILITYTIMEOUT",
      description: "OUT Facility  Time OUT",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "5",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1653",
      object_id: "column-1653",
      name: "OUTFACILITYDATEIN",
      name_without_path: "OUTFACILITYDATEIN",
      description: "OUT Facility  Date IN",
      is_pk: false,
      is_identity: false,
      data_type: "datetime",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1654",
      object_id: "column-1654",
      name: "OUTFACILITYTIMEIN",
      name_without_path: "OUTFACILITYTIMEIN",
      description: "OUT Facility  Time IN",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "5",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1655",
      object_id: "column-1655",
      name: "OUTFACILITYREASON",
      name_without_path: "OUTFACILITYREASON",
      description: "VALUEX from 'LOGEVENT' DVT",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "2",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1656",
      object_id: "column-1656",
      name: "OUTFACILITYCMT",
      name_without_path: "OUTFACILITYCMT",
      description: "OUT Facility CMT",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "80",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1657",
      object_id: "column-1657",
      name: "BOOF1OFCRNUM",
      name_without_path: "BOOF1OFCRNUM",
      description: "BOOF1Officer Num",
      is_pk: false,
      is_identity: false,
      data_type: "int",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1658",
      object_id: "column-1658",
      name: "BOOF2OFCRNUM",
      name_without_path: "BOOF2OFCRNUM",
      description: "BOOF2Officer Num",
      is_pk: false,
      is_identity: false,
      data_type: "int",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1659",
      object_id: "column-1659",
      name: "RECVOF1OFCRNUM",
      name_without_path: "RECVOF1OFCRNUM",
      description: "RECVOF1Officer Num",
      is_pk: false,
      is_identity: false,
      data_type: "int",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1660",
      object_id: "column-1660",
      name: "RECVOF2OFCRNUM",
      name_without_path: "RECVOF2OFCRNUM",
      description: "RECVOF2Officer Num",
      is_pk: false,
      is_identity: false,
      data_type: "int",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1568",
      object_id: "column-1568",
      name: "SEAROF1OFCRNUM",
      name_without_path: "SEAROF1OFCRNUM",
      description: "SEAROF1Officer Num",
      is_pk: false,
      is_identity: false,
      data_type: "int",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1569",
      object_id: "column-1569",
      name: "OUTOFCRNUM",
      name_without_path: "OUTOFCRNUM",
      description: "OUTOfficer Num",
      is_pk: false,
      is_identity: false,
      data_type: "int",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1570",
      object_id: "column-1570",
      name: "NOOFFENSESREQUIRED",
      name_without_path: "NOOFFENSESREQUIRED",
      description: "NO Offense S Require D",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "1",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1571",
      object_id: "column-1571",
      name: "SEAROF2OFCRNUM",
      name_without_path: "SEAROF2OFCRNUM",
      description: "SEAROF2Officer Num",
      is_pk: false,
      is_identity: false,
      data_type: "int",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1572",
      object_id: "column-1572",
      name: "TPOF1OFCRNUM",
      name_without_path: "TPOF1OFCRNUM",
      description: "TPOF1Officer Num",
      is_pk: false,
      is_identity: false,
      data_type: "int",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1573",
      object_id: "column-1573",
      name: "TPOF2OFCRNUM",
      name_without_path: "TPOF2OFCRNUM",
      description: "TPOF2Officer Num",
      is_pk: false,
      is_identity: false,
      data_type: "int",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1574",
      object_id: "column-1574",
      name: "BILLINGAGENCY",
      name_without_path: "BILLINGAGENCY",
      description: "Billing Agency",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "30",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1575",
      object_id: "column-1575",
      name: "TOTAL_BAIL",
      name_without_path: "TOTAL_BAIL",
      description: "Total   Bail",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "20",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1576",
      object_id: "column-1576",
      name: "INCLUDEINCITIZENRIMS",
      name_without_path: "INCLUDEINCITIZENRIMS",
      description: "Include IN Citizen  RIMS",
      is_pk: false,
      is_identity: false,
      data_type: "char",
      data_length: "1",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1577",
      object_id: "column-1577",
      name: "SWANCLASSIFICATION",
      name_without_path: "SWANCLASSIFICATION",
      description: "Trinity Commissary Classifications (Jail Module)",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "25",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1578",
      object_id: "column-1578",
      name: "SWANRESTRICTION",
      name_without_path: "SWANRESTRICTION",
      description: "Trinity Commissary Restrictions (Jail Module)",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "25",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1579",
      object_id: "column-1579",
      name: "SWANCREATED",
      name_without_path: "SWANCREATED",
      description: "SWAN Created",
      is_pk: false,
      is_identity: false,
      data_type: "char",
      data_length: "1",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1580",
      object_id: "column-1580",
      name: "swansoncreated",
      name_without_path: "swansoncreated",
      description: "SWANS on Created",
      is_pk: false,
      is_identity: false,
      data_type: "char",
      data_length: "1",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1581",
      object_id: "column-1581",
      name: "PHONECREATED",
      name_without_path: "PHONECREATED",
      description: "Phone  Created",
      is_pk: false,
      is_identity: false,
      data_type: "char",
      data_length: "1",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1582",
      object_id: "column-1582",
      name: "MEDICALCREATED",
      name_without_path: "MEDICALCREATED",
      description: "Medical  Created",
      is_pk: false,
      is_identity: false,
      data_type: "char",
      data_length: "1",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1583",
      object_id: "column-1583",
      name: "ARRIVALDATE",
      name_without_path: "ARRIVALDATE",
      description: "Arrival  Date",
      is_pk: false,
      is_identity: false,
      data_type: "datetime",
      data_length: null,
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1584",
      object_id: "column-1584",
      name: "ARRIVALTIME",
      name_without_path: "ARRIVALTIME",
      description: "Arrival Time",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "5",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1585",
      object_id: "column-1585",
      name: "BOOKCIRC1",
      name_without_path: "BOOKCIRC1",
      description: "Special Circumstances - Booking (Jail Module)",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "2",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1586",
      object_id: "column-1586",
      name: "BOOKCIRC2",
      name_without_path: "BOOKCIRC2",
      description: "Special Circumstances - Booking (Jail Module)",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "2",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1587",
      object_id: "column-1587",
      name: "BOOKCIRC3",
      name_without_path: "BOOKCIRC3",
      description: "Special Circumstances - Booking (Jail Module)",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "2",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1588",
      object_id: "column-1588",
      name: "BOOKCIRC4",
      name_without_path: "BOOKCIRC4",
      description: "Booking Circ4",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "2",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1589",
      object_id: "column-1589",
      name: "MONITORDISP",
      name_without_path: "MONITORDISP",
      description: "Monitor DISP",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "10",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1590",
      object_id: "column-1590",
      name: "NOCITRIMSREASON",
      name_without_path: "NOCITRIMSREASON",
      description: "No CitRIMS Reason",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "40",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1591",
      object_id: "column-1591",
      name: "HELDFOR",
      name_without_path: "HELDFOR",
      description: "Held For",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "2",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1592",
      object_id: "column-1592",
      name: "CELLCLASS",
      name_without_path: "CELLCLASS",
      description: "Inmate Custody Classification",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "10",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
    {
      id: "column-1593",
      object_id: "column-1593",
      name: "BOOKCLSST",
      name_without_path: "BOOKCLSST",
      description: "Inmate Classification Status",
      is_pk: false,
      is_identity: false,
      data_type: "varchar",
      data_length: "2",
      is_nullable: true,
      computed_formula: null,
      default_value: null,
      path: null,
      level: 1,
      item_type: "COLUMN",
      is_user_defined: false,
      custom_fields: {},
      linked_terms: [],
      references: [],
      linked_lookup: null,
    },
  ],
  relations: [
    {
      name: "FK_INM_BOOKING_ALPHAID",
      title: null,
      description: null,
      is_user_defined: false,
      foreign_table: "INM_BOOKING",
      foreign_table_show_schema: "dbo.INM_BOOKING",
      foreign_table_verbose: "INM_BOOKING",
      foreign_table_verbose_show_schema: "dbo.INM_BOOKING",
      foreign_table_object_id: "t69",
      primary_table: "ALPHA",
      primary_table_show_schema: "dbo.ALPHA",
      primary_table_verbose: "ALPHA",
      primary_table_verbose_show_schema: "dbo.ALPHA",
      primary_table_object_id: "t412",
      pk_cardinality: "1x",
      fk_cardinality: "mx",
      constraints: [
        {
          primary_column_path: null,
          primary_column: "ID",
          foreign_column_path: null,
          foreign_column: "ALPHAID",
        },
      ],
      custom_fields: {},
    },
    {
      name: "FK_INM_ALERTS_BOOK_NO",
      title: null,
      description: null,
      is_user_defined: false,
      foreign_table: "INM_ALERTS",
      foreign_table_show_schema: "dbo.INM_ALERTS",
      foreign_table_verbose: "INM_ALERTS",
      foreign_table_verbose_show_schema: "dbo.INM_ALERTS",
      foreign_table_object_id: "t238",
      primary_table: "INM_BOOKING",
      primary_table_show_schema: "dbo.INM_BOOKING",
      primary_table_verbose: "INM_BOOKING",
      primary_table_verbose_show_schema: "dbo.INM_BOOKING",
      primary_table_object_id: "t69",
      pk_cardinality: "1x",
      fk_cardinality: "mx",
      constraints: [
        {
          primary_column_path: null,
          primary_column: "BOOKNO",
          foreign_column_path: null,
          foreign_column: "BOOK_NO",
        },
      ],
      custom_fields: {},
    },
    {
      name: "FK_INM_APPT_REQUESTS_BOOKNO",
      title: null,
      description: null,
      is_user_defined: false,
      foreign_table: "INM_APPT_REQUESTS",
      foreign_table_show_schema: "dbo.INM_APPT_REQUESTS",
      foreign_table_verbose: "INM_APPT_REQUESTS",
      foreign_table_verbose_show_schema: "dbo.INM_APPT_REQUESTS",
      foreign_table_object_id: "t246",
      primary_table: "INM_BOOKING",
      primary_table_show_schema: "dbo.INM_BOOKING",
      primary_table_verbose: "INM_BOOKING",
      primary_table_verbose_show_schema: "dbo.INM_BOOKING",
      primary_table_object_id: "t69",
      pk_cardinality: "1x",
      fk_cardinality: "mx",
      constraints: [
        {
          primary_column_path: null,
          primary_column: "BOOKNO",
          foreign_column_path: null,
          foreign_column: "BOOK_NO",
        },
      ],
      custom_fields: {},
    },
    {
      name: "FK_INM_ATTACHMENTS_BOOKNO",
      title: null,
      description: null,
      is_user_defined: false,
      foreign_table: "INM_ATTACHMENTS",
      foreign_table_show_schema: "dbo.INM_ATTACHMENTS",
      foreign_table_verbose: "INM_ATTACHMENTS",
      foreign_table_verbose_show_schema: "dbo.INM_ATTACHMENTS",
      foreign_table_object_id: "t252",
      primary_table: "INM_BOOKING",
      primary_table_show_schema: "dbo.INM_BOOKING",
      primary_table_verbose: "INM_BOOKING",
      primary_table_verbose_show_schema: "dbo.INM_BOOKING",
      primary_table_object_id: "t69",
      pk_cardinality: "1x",
      fk_cardinality: "mx",
      constraints: [
        {
          primary_column_path: null,
          primary_column: "BOOKNO",
          foreign_column_path: null,
          foreign_column: "BOOK_NO",
        },
      ],
      custom_fields: {},
    },
    {
      name: "FK_INM_AUDIT_BOOKNO",
      title: null,
      description: null,
      is_user_defined: false,
      foreign_table: "INM_AUDIT",
      foreign_table_show_schema: "dbo.INM_AUDIT",
      foreign_table_verbose: "INM_AUDIT",
      foreign_table_verbose_show_schema: "dbo.INM_AUDIT",
      foreign_table_object_id: "t258",
      primary_table: "INM_BOOKING",
      primary_table_show_schema: "dbo.INM_BOOKING",
      primary_table_verbose: "INM_BOOKING",
      primary_table_verbose_show_schema: "dbo.INM_BOOKING",
      primary_table_object_id: "t69",
      pk_cardinality: "1x",
      fk_cardinality: "mx",
      constraints: [
        {
          primary_column_path: null,
          primary_column: "BOOKNO",
          foreign_column_path: null,
          foreign_column: "BOOK_NO",
        },
      ],
      custom_fields: {},
    },
    {
      name: "FK_INM_AUTHORIZED_ITEMS_BOOKNO",
      title: null,
      description: null,
      is_user_defined: false,
      foreign_table: "INM_AUTHORIZED_ITEMS",
      foreign_table_show_schema: "dbo.INM_AUTHORIZED_ITEMS",
      foreign_table_verbose: "INM_AUTHORIZED_ITEMS",
      foreign_table_verbose_show_schema: "dbo.INM_AUTHORIZED_ITEMS",
      foreign_table_object_id: "t64",
      primary_table: "INM_BOOKING",
      primary_table_show_schema: "dbo.INM_BOOKING",
      primary_table_verbose: "INM_BOOKING",
      primary_table_verbose_show_schema: "dbo.INM_BOOKING",
      primary_table_object_id: "t69",
      pk_cardinality: "1x",
      fk_cardinality: "mx",
      constraints: [
        {
          primary_column_path: null,
          primary_column: "BOOKNO",
          foreign_column_path: null,
          foreign_column: "BOOK_NO",
        },
      ],
      custom_fields: {},
    },
    {
      name: "FK_INM_BOOKING_SCHEDULED_BOOK_NO",
      title: null,
      description: null,
      is_user_defined: false,
      foreign_table: "INM_BOOKING_SCHEDULED",
      foreign_table_show_schema: "dbo.INM_BOOKING_SCHEDULED",
      foreign_table_verbose: "INM_BOOKING_SCHEDULED",
      foreign_table_verbose_show_schema: "dbo.INM_BOOKING_SCHEDULED",
      foreign_table_object_id: "t261",
      primary_table: "INM_BOOKING",
      primary_table_show_schema: "dbo.INM_BOOKING",
      primary_table_verbose: "INM_BOOKING",
      primary_table_verbose_show_schema: "dbo.INM_BOOKING",
      primary_table_object_id: "t69",
      pk_cardinality: "1x",
      fk_cardinality: "mx",
      constraints: [
        {
          primary_column_path: null,
          primary_column: "BOOKNO",
          foreign_column_path: null,
          foreign_column: "BOOK_NO",
        },
      ],
      custom_fields: {},
    },
    {
      name: "FK_INM_CELL_LOG_BOOKNO",
      title: null,
      description: null,
      is_user_defined: false,
      foreign_table: "INM_CELL_LOG",
      foreign_table_show_schema: "dbo.INM_CELL_LOG",
      foreign_table_verbose: "INM_CELL_LOG",
      foreign_table_verbose_show_schema: "dbo.INM_CELL_LOG",
      foreign_table_object_id: "t267",
      primary_table: "INM_BOOKING",
      primary_table_show_schema: "dbo.INM_BOOKING",
      primary_table_verbose: "INM_BOOKING",
      primary_table_verbose_show_schema: "dbo.INM_BOOKING",
      primary_table_object_id: "t69",
      pk_cardinality: "1x",
      fk_cardinality: "mx",
      constraints: [
        {
          primary_column_path: null,
          primary_column: "BOOKNO",
          foreign_column_path: null,
          foreign_column: "BOOK_NO",
        },
      ],
      custom_fields: {},
    },
    {
      name: "FK_INM_CHARGES_BOOKNO",
      title: null,
      description: null,
      is_user_defined: false,
      foreign_table: "INM_CHARGES",
      foreign_table_show_schema: "dbo.INM_CHARGES",
      foreign_table_verbose: "INM_CHARGES",
      foreign_table_verbose_show_schema: "dbo.INM_CHARGES",
      foreign_table_object_id: "t220",
      primary_table: "INM_BOOKING",
      primary_table_show_schema: "dbo.INM_BOOKING",
      primary_table_verbose: "INM_BOOKING",
      primary_table_verbose_show_schema: "dbo.INM_BOOKING",
      primary_table_object_id: "t69",
      pk_cardinality: "1x",
      fk_cardinality: "mx",
      constraints: [
        {
          primary_column_path: null,
          primary_column: "BOOKNO",
          foreign_column_path: null,
          foreign_column: "BOOK_NO",
        },
      ],
      custom_fields: {},
    },
    {
      name: "FK_INM_COMORDER_BOOKNO",
      title: null,
      description: null,
      is_user_defined: false,
      foreign_table: "INM_COMORDER",
      foreign_table_show_schema: "dbo.INM_COMORDER",
      foreign_table_verbose: "INM_COMORDER",
      foreign_table_verbose_show_schema: "dbo.INM_COMORDER",
      foreign_table_object_id: "t148",
      primary_table: "INM_BOOKING",
      primary_table_show_schema: "dbo.INM_BOOKING",
      primary_table_verbose: "INM_BOOKING",
      primary_table_verbose_show_schema: "dbo.INM_BOOKING",
      primary_table_object_id: "t69",
      pk_cardinality: "1x",
      fk_cardinality: "mx",
      constraints: [
        {
          primary_column_path: null,
          primary_column: "BOOKNO",
          foreign_column_path: null,
          foreign_column: "BOOKNO",
        },
      ],
      custom_fields: {},
    },
    {
      name: "FK_INM_COURT_LOG_BOOKNO",
      title: null,
      description: null,
      is_user_defined: false,
      foreign_table: "INM_COURT_LOG",
      foreign_table_show_schema: "dbo.INM_COURT_LOG",
      foreign_table_verbose: "INM_COURT_LOG",
      foreign_table_verbose_show_schema: "dbo.INM_COURT_LOG",
      foreign_table_object_id: "t290",
      primary_table: "INM_BOOKING",
      primary_table_show_schema: "dbo.INM_BOOKING",
      primary_table_verbose: "INM_BOOKING",
      primary_table_verbose_show_schema: "dbo.INM_BOOKING",
      primary_table_object_id: "t69",
      pk_cardinality: "1x",
      fk_cardinality: "mx",
      constraints: [
        {
          primary_column_path: null,
          primary_column: "BOOKNO",
          foreign_column_path: null,
          foreign_column: "BOOK_NO",
        },
      ],
      custom_fields: {},
    },
    {
      name: "FK_INM_DISCIPLINARY_BOOKNO",
      title: null,
      description: null,
      is_user_defined: false,
      foreign_table: "INM_DISCIPLINARY",
      foreign_table_show_schema: "dbo.INM_DISCIPLINARY",
      foreign_table_verbose: "INM_DISCIPLINARY",
      foreign_table_verbose_show_schema: "dbo.INM_DISCIPLINARY",
      foreign_table_object_id: "t227",
      primary_table: "INM_BOOKING",
      primary_table_show_schema: "dbo.INM_BOOKING",
      primary_table_verbose: "INM_BOOKING",
      primary_table_verbose_show_schema: "dbo.INM_BOOKING",
      primary_table_object_id: "t69",
      pk_cardinality: "1x",
      fk_cardinality: "mx",
      constraints: [
        {
          primary_column_path: null,
          primary_column: "BOOKNO",
          foreign_column_path: null,
          foreign_column: "BOOK_NO",
        },
      ],
      custom_fields: {},
    },
    {
      name: "FK_INM_DISCIPLINARY_HEARINGS_BOOKNO",
      title: null,
      description: null,
      is_user_defined: false,
      foreign_table: "INM_DISCIPLINARY_HEARINGS",
      foreign_table_show_schema: "dbo.INM_DISCIPLINARY_HEARINGS",
      foreign_table_verbose: "INM_DISCIPLINARY_HEARINGS",
      foreign_table_verbose_show_schema: "dbo.INM_DISCIPLINARY_HEARINGS",
      foreign_table_object_id: "t233",
      primary_table: "INM_BOOKING",
      primary_table_show_schema: "dbo.INM_BOOKING",
      primary_table_verbose: "INM_BOOKING",
      primary_table_verbose_show_schema: "dbo.INM_BOOKING",
      primary_table_object_id: "t69",
      pk_cardinality: "1x",
      fk_cardinality: "mx",
      constraints: [
        {
          primary_column_path: null,
          primary_column: "BOOKNO",
          foreign_column_path: null,
          foreign_column: "BOOK_NO",
        },
      ],
      custom_fields: {},
    },
    {
      name: "FK_INM_INT_QUESTIONS_BOOKNO",
      title: null,
      description: null,
      is_user_defined: false,
      foreign_table: "INM_INT_QUESTIONS",
      foreign_table_show_schema: "dbo.INM_INT_QUESTIONS",
      foreign_table_verbose: "INM_INT_QUESTIONS",
      foreign_table_verbose_show_schema: "dbo.INM_INT_QUESTIONS",
      foreign_table_object_id: "t32",
      primary_table: "INM_BOOKING",
      primary_table_show_schema: "dbo.INM_BOOKING",
      primary_table_verbose: "INM_BOOKING",
      primary_table_verbose_show_schema: "dbo.INM_BOOKING",
      primary_table_object_id: "t69",
      pk_cardinality: "1x",
      fk_cardinality: "mx",
      constraints: [
        {
          primary_column_path: null,
          primary_column: "BOOKNO",
          foreign_column_path: null,
          foreign_column: "BOOK_NO",
        },
      ],
      custom_fields: {},
    },
    {
      name: "FK_INM_INT_SUBQUESTIONS_BOOK_NO",
      title: null,
      description: null,
      is_user_defined: false,
      foreign_table: "INM_INT_SUBQUESTIONS",
      foreign_table_show_schema: "dbo.INM_INT_SUBQUESTIONS",
      foreign_table_verbose: "INM_INT_SUBQUESTIONS",
      foreign_table_verbose_show_schema: "dbo.INM_INT_SUBQUESTIONS",
      foreign_table_object_id: "t114",
      primary_table: "INM_BOOKING",
      primary_table_show_schema: "dbo.INM_BOOKING",
      primary_table_verbose: "INM_BOOKING",
      primary_table_verbose_show_schema: "dbo.INM_BOOKING",
      primary_table_object_id: "t69",
      pk_cardinality: "1x",
      fk_cardinality: "mx",
      constraints: [
        {
          primary_column_path: null,
          primary_column: "BOOKNO",
          foreign_column_path: null,
          foreign_column: "BOOK_NO",
        },
      ],
      custom_fields: {},
    },
    {
      name: "FK_INM_INTAKE_PROPERTY_BOOKNO",
      title: null,
      description: null,
      is_user_defined: false,
      foreign_table: "INM_INTAKE_PROPERTY",
      foreign_table_show_schema: "dbo.INM_INTAKE_PROPERTY",
      foreign_table_verbose: "INM_INTAKE_PROPERTY",
      foreign_table_verbose_show_schema: "dbo.INM_INTAKE_PROPERTY",
      foreign_table_object_id: "t164",
      primary_table: "INM_BOOKING",
      primary_table_show_schema: "dbo.INM_BOOKING",
      primary_table_verbose: "INM_BOOKING",
      primary_table_verbose_show_schema: "dbo.INM_BOOKING",
      primary_table_object_id: "t69",
      pk_cardinality: "1x",
      fk_cardinality: "mx",
      constraints: [
        {
          primary_column_path: null,
          primary_column: "BOOKNO",
          foreign_column_path: null,
          foreign_column: "BOOK_NO",
        },
      ],
      custom_fields: {},
    },
    {
      name: "FK_INM_KEEP_AWAY_BOOKNO",
      title: null,
      description: null,
      is_user_defined: false,
      foreign_table: "INM_KEEP_AWAY",
      foreign_table_show_schema: "dbo.INM_KEEP_AWAY",
      foreign_table_verbose: "INM_KEEP_AWAY",
      foreign_table_verbose_show_schema: "dbo.INM_KEEP_AWAY",
      foreign_table_object_id: "t245",
      primary_table: "INM_BOOKING",
      primary_table_show_schema: "dbo.INM_BOOKING",
      primary_table_verbose: "INM_BOOKING",
      primary_table_verbose_show_schema: "dbo.INM_BOOKING",
      primary_table_object_id: "t69",
      pk_cardinality: "1x",
      fk_cardinality: "mx",
      constraints: [
        {
          primary_column_path: null,
          primary_column: "BOOKNO",
          foreign_column_path: null,
          foreign_column: "BOOK_NO",
        },
      ],
      custom_fields: {},
    },
    {
      name: "FK_INM_MAIL_LOG_BOOKNO",
      title: null,
      description: null,
      is_user_defined: false,
      foreign_table: "INM_MAIL_LOG",
      foreign_table_show_schema: "dbo.INM_MAIL_LOG",
      foreign_table_verbose: "INM_MAIL_LOG",
      foreign_table_verbose_show_schema: "dbo.INM_MAIL_LOG",
      foreign_table_object_id: "t86",
      primary_table: "INM_BOOKING",
      primary_table_show_schema: "dbo.INM_BOOKING",
      primary_table_verbose: "INM_BOOKING",
      primary_table_verbose_show_schema: "dbo.INM_BOOKING",
      primary_table_object_id: "t69",
      pk_cardinality: "1x",
      fk_cardinality: "mx",
      constraints: [
        {
          primary_column_path: null,
          primary_column: "BOOKNO",
          foreign_column_path: null,
          foreign_column: "BOOK_NO",
        },
      ],
      custom_fields: {},
    },
    {
      name: "FK_INM_MEDIA_LOG_BOOKNO",
      title: null,
      description: null,
      is_user_defined: false,
      foreign_table: "INM_MEDIA_LOG",
      foreign_table_show_schema: "dbo.INM_MEDIA_LOG",
      foreign_table_verbose: "INM_MEDIA_LOG",
      foreign_table_verbose_show_schema: "dbo.INM_MEDIA_LOG",
      foreign_table_object_id: "t209",
      primary_table: "INM_BOOKING",
      primary_table_show_schema: "dbo.INM_BOOKING",
      primary_table_verbose: "INM_BOOKING",
      primary_table_verbose_show_schema: "dbo.INM_BOOKING",
      primary_table_object_id: "t69",
      pk_cardinality: "1x",
      fk_cardinality: "mx",
      constraints: [
        {
          primary_column_path: null,
          primary_column: "BOOKNO",
          foreign_column_path: null,
          foreign_column: "BOOK_NO",
        },
      ],
      custom_fields: {},
    },
    {
      name: "FK_INM_MEDICAL_ALLERGIES_BOOKNO",
      title: null,
      description: null,
      is_user_defined: false,
      foreign_table: "INM_MEDICAL_ALLERGIES",
      foreign_table_show_schema: "dbo.INM_MEDICAL_ALLERGIES",
      foreign_table_verbose: "INM_MEDICAL_ALLERGIES",
      foreign_table_verbose_show_schema: "dbo.INM_MEDICAL_ALLERGIES",
      foreign_table_object_id: "t212",
      primary_table: "INM_BOOKING",
      primary_table_show_schema: "dbo.INM_BOOKING",
      primary_table_verbose: "INM_BOOKING",
      primary_table_verbose_show_schema: "dbo.INM_BOOKING",
      primary_table_object_id: "t69",
      pk_cardinality: "1x",
      fk_cardinality: "mx",
      constraints: [
        {
          primary_column_path: null,
          primary_column: "BOOKNO",
          foreign_column_path: null,
          foreign_column: "BOOK_NO",
        },
      ],
      custom_fields: {},
    },
    {
      name: "FK_INM_MEDICAL_CHART_BOOKNO",
      title: null,
      description: null,
      is_user_defined: false,
      foreign_table: "INM_MEDICAL_CHART",
      foreign_table_show_schema: "dbo.INM_MEDICAL_CHART",
      foreign_table_verbose: "INM_MEDICAL_CHART",
      foreign_table_verbose_show_schema: "dbo.INM_MEDICAL_CHART",
      foreign_table_object_id: "t216",
      primary_table: "INM_BOOKING",
      primary_table_show_schema: "dbo.INM_BOOKING",
      primary_table_verbose: "INM_BOOKING",
      primary_table_verbose_show_schema: "dbo.INM_BOOKING",
      primary_table_object_id: "t69",
      pk_cardinality: "1x",
      fk_cardinality: "mx",
      constraints: [
        {
          primary_column_path: null,
          primary_column: "BOOKNO",
          foreign_column_path: null,
          foreign_column: "BOOK_NO",
        },
      ],
      custom_fields: {},
    },
    {
      name: "FK_INM_MEDICAL_DIET_BOOK_NO",
      title: null,
      description: null,
      is_user_defined: false,
      foreign_table: "INM_MEDICAL_DIET",
      foreign_table_show_schema: "dbo.INM_MEDICAL_DIET",
      foreign_table_verbose: "INM_MEDICAL_DIET",
      foreign_table_verbose_show_schema: "dbo.INM_MEDICAL_DIET",
      foreign_table_object_id: "t143",
      primary_table: "INM_BOOKING",
      primary_table_show_schema: "dbo.INM_BOOKING",
      primary_table_verbose: "INM_BOOKING",
      primary_table_verbose_show_schema: "dbo.INM_BOOKING",
      primary_table_object_id: "t69",
      pk_cardinality: "1x",
      fk_cardinality: "mx",
      constraints: [
        {
          primary_column_path: null,
          primary_column: "BOOKNO",
          foreign_column_path: null,
          foreign_column: "BOOK_NO",
        },
      ],
      custom_fields: {},
    },
    {
      name: "FK_INM_MEDICAL_GLUCOSE_BOOKNO",
      title: null,
      description: null,
      is_user_defined: false,
      foreign_table: "INM_MEDICAL_GLUCOSE",
      foreign_table_show_schema: "dbo.INM_MEDICAL_GLUCOSE",
      foreign_table_verbose: "INM_MEDICAL_GLUCOSE",
      foreign_table_verbose_show_schema: "dbo.INM_MEDICAL_GLUCOSE",
      foreign_table_object_id: "t107",
      primary_table: "INM_BOOKING",
      primary_table_show_schema: "dbo.INM_BOOKING",
      primary_table_verbose: "INM_BOOKING",
      primary_table_verbose_show_schema: "dbo.INM_BOOKING",
      primary_table_object_id: "t69",
      pk_cardinality: "1x",
      fk_cardinality: "mx",
      constraints: [
        {
          primary_column_path: null,
          primary_column: "BOOKNO",
          foreign_column_path: null,
          foreign_column: "BOOK_NO",
        },
      ],
      custom_fields: {},
    },
    {
      name: "FK_INM_MEDICAL_LOG_BOOKNO",
      title: null,
      description: null,
      is_user_defined: false,
      foreign_table: "INM_MEDICAL_LOG",
      foreign_table_show_schema: "dbo.INM_MEDICAL_LOG",
      foreign_table_verbose: "INM_MEDICAL_LOG",
      foreign_table_verbose_show_schema: "dbo.INM_MEDICAL_LOG",
      foreign_table_object_id: "t251",
      primary_table: "INM_BOOKING",
      primary_table_show_schema: "dbo.INM_BOOKING",
      primary_table_verbose: "INM_BOOKING",
      primary_table_verbose_show_schema: "dbo.INM_BOOKING",
      primary_table_object_id: "t69",
      pk_cardinality: "1x",
      fk_cardinality: "mx",
      constraints: [
        {
          primary_column_path: null,
          primary_column: "BOOKNO",
          foreign_column_path: null,
          foreign_column: "BOOK_NO",
        },
      ],
      custom_fields: {},
    },
    {
      name: "FK_INM_MEDICAL_TB_BOOKNO",
      title: null,
      description: null,
      is_user_defined: false,
      foreign_table: "INM_MEDICAL_TB",
      foreign_table_show_schema: "dbo.INM_MEDICAL_TB",
      foreign_table_verbose: "INM_MEDICAL_TB",
      foreign_table_verbose_show_schema: "dbo.INM_MEDICAL_TB",
      foreign_table_object_id: "t118",
      primary_table: "INM_BOOKING",
      primary_table_show_schema: "dbo.INM_BOOKING",
      primary_table_verbose: "INM_BOOKING",
      primary_table_verbose_show_schema: "dbo.INM_BOOKING",
      primary_table_object_id: "t69",
      pk_cardinality: "1x",
      fk_cardinality: "mx",
      constraints: [
        {
          primary_column_path: null,
          primary_column: "BOOKNO",
          foreign_column_path: null,
          foreign_column: "BOOK_NO",
        },
      ],
      custom_fields: {},
    },
    {
      name: "FK_INM_MEDLIST_BOOKNO",
      title: null,
      description: null,
      is_user_defined: false,
      foreign_table: "INM_MEDLIST",
      foreign_table_show_schema: "dbo.INM_MEDLIST",
      foreign_table_verbose: "INM_MEDLIST",
      foreign_table_verbose_show_schema: "dbo.INM_MEDLIST",
      foreign_table_object_id: "t257",
      primary_table: "INM_BOOKING",
      primary_table_show_schema: "dbo.INM_BOOKING",
      primary_table_verbose: "INM_BOOKING",
      primary_table_verbose_show_schema: "dbo.INM_BOOKING",
      primary_table_object_id: "t69",
      pk_cardinality: "1x",
      fk_cardinality: "mx",
      constraints: [
        {
          primary_column_path: null,
          primary_column: "BOOKNO",
          foreign_column_path: null,
          foreign_column: "BOOKNO",
        },
      ],
      custom_fields: {},
    },
    {
      name: "FK_INM_PEOPLE_BOOKNO",
      title: null,
      description: null,
      is_user_defined: false,
      foreign_table: "INM_PEOPLE",
      foreign_table_show_schema: "dbo.INM_PEOPLE",
      foreign_table_verbose: "INM_PEOPLE",
      foreign_table_verbose_show_schema: "dbo.INM_PEOPLE",
      foreign_table_object_id: "t361",
      primary_table: "INM_BOOKING",
      primary_table_show_schema: "dbo.INM_BOOKING",
      primary_table_verbose: "INM_BOOKING",
      primary_table_verbose_show_schema: "dbo.INM_BOOKING",
      primary_table_object_id: "t69",
      pk_cardinality: "1x",
      fk_cardinality: "mx",
      constraints: [
        {
          primary_column_path: null,
          primary_column: "BOOKNO",
          foreign_column_path: null,
          foreign_column: "BOOK_NO",
        },
      ],
      custom_fields: {},
    },
    {
      name: "FK_INM_PEOPLE_LOG_BOOKNO",
      title: null,
      description: null,
      is_user_defined: false,
      foreign_table: "INM_PEOPLE_LOG",
      foreign_table_show_schema: "dbo.INM_PEOPLE_LOG",
      foreign_table_verbose: "INM_PEOPLE_LOG",
      foreign_table_verbose_show_schema: "dbo.INM_PEOPLE_LOG",
      foreign_table_object_id: "t370",
      primary_table: "INM_BOOKING",
      primary_table_show_schema: "dbo.INM_BOOKING",
      primary_table_verbose: "INM_BOOKING",
      primary_table_verbose_show_schema: "dbo.INM_BOOKING",
      primary_table_object_id: "t69",
      pk_cardinality: "1x",
      fk_cardinality: "mx",
      constraints: [
        {
          primary_column_path: null,
          primary_column: "BOOKNO",
          foreign_column_path: null,
          foreign_column: "BOOK_NO",
        },
      ],
      custom_fields: {},
    },
    {
      name: "FK_INM_PHONE_ACCESS_BOOKNO",
      title: null,
      description: null,
      is_user_defined: false,
      foreign_table: "INM_PHONE_ACCESS",
      foreign_table_show_schema: "dbo.INM_PHONE_ACCESS",
      foreign_table_verbose: "INM_PHONE_ACCESS",
      foreign_table_verbose_show_schema: "dbo.INM_PHONE_ACCESS",
      foreign_table_object_id: "t20",
      primary_table: "INM_BOOKING",
      primary_table_show_schema: "dbo.INM_BOOKING",
      primary_table_verbose: "INM_BOOKING",
      primary_table_verbose_show_schema: "dbo.INM_BOOKING",
      primary_table_object_id: "t69",
      pk_cardinality: "1x",
      fk_cardinality: "mx",
      constraints: [
        {
          primary_column_path: null,
          primary_column: "BOOKNO",
          foreign_column_path: null,
          foreign_column: "BOOK_NO",
        },
      ],
      custom_fields: {},
    },
    {
      name: "FK_INM_PHONE_LOG_BOOKNO",
      title: null,
      description: null,
      is_user_defined: false,
      foreign_table: "INM_PHONE_LOG",
      foreign_table_show_schema: "dbo.INM_PHONE_LOG",
      foreign_table_verbose: "INM_PHONE_LOG",
      foreign_table_verbose_show_schema: "dbo.INM_PHONE_LOG",
      foreign_table_object_id: "t411",
      primary_table: "INM_BOOKING",
      primary_table_show_schema: "dbo.INM_BOOKING",
      primary_table_verbose: "INM_BOOKING",
      primary_table_verbose_show_schema: "dbo.INM_BOOKING",
      primary_table_object_id: "t69",
      pk_cardinality: "1x",
      fk_cardinality: "mx",
      constraints: [
        {
          primary_column_path: null,
          primary_column: "BOOKNO",
          foreign_column_path: null,
          foreign_column: "BOOK_NO",
        },
      ],
      custom_fields: {},
    },
    {
      name: "FK_INM_REQUEST_BOOK_NO",
      title: null,
      description: null,
      is_user_defined: false,
      foreign_table: "INM_REQUEST",
      foreign_table_show_schema: "dbo.INM_REQUEST",
      foreign_table_verbose: "INM_REQUEST",
      foreign_table_verbose_show_schema: "dbo.INM_REQUEST",
      foreign_table_object_id: "t298",
      primary_table: "INM_BOOKING",
      primary_table_show_schema: "dbo.INM_BOOKING",
      primary_table_verbose: "INM_BOOKING",
      primary_table_verbose_show_schema: "dbo.INM_BOOKING",
      primary_table_object_id: "t69",
      pk_cardinality: "1x",
      fk_cardinality: "mx",
      constraints: [
        {
          primary_column_path: null,
          primary_column: "BOOKNO",
          foreign_column_path: null,
          foreign_column: "BOOK_NO",
        },
      ],
      custom_fields: {},
    },
    {
      name: "FK_INM_SHIFT_LOG_BOOKNO",
      title: null,
      description: null,
      is_user_defined: false,
      foreign_table: "INM_SHIFT_LOG",
      foreign_table_show_schema: "dbo.INM_SHIFT_LOG",
      foreign_table_verbose: "INM_SHIFT_LOG",
      foreign_table_verbose_show_schema: "dbo.INM_SHIFT_LOG",
      foreign_table_object_id: "t188",
      primary_table: "INM_BOOKING",
      primary_table_show_schema: "dbo.INM_BOOKING",
      primary_table_verbose: "INM_BOOKING",
      primary_table_verbose_show_schema: "dbo.INM_BOOKING",
      primary_table_object_id: "t69",
      pk_cardinality: "1x",
      fk_cardinality: "mx",
      constraints: [
        {
          primary_column_path: null,
          primary_column: "BOOKNO",
          foreign_column_path: null,
          foreign_column: "BOOK_NO",
        },
      ],
      custom_fields: {},
    },
    {
      name: "FK_INM_STAY_CHARGES_BOOKNO",
      title: null,
      description: null,
      is_user_defined: false,
      foreign_table: "INM_STAY_CHARGES",
      foreign_table_show_schema: "dbo.INM_STAY_CHARGES",
      foreign_table_verbose: "INM_STAY_CHARGES",
      foreign_table_verbose_show_schema: "dbo.INM_STAY_CHARGES",
      foreign_table_object_id: "t197",
      primary_table: "INM_BOOKING",
      primary_table_show_schema: "dbo.INM_BOOKING",
      primary_table_verbose: "INM_BOOKING",
      primary_table_verbose_show_schema: "dbo.INM_BOOKING",
      primary_table_object_id: "t69",
      pk_cardinality: "1x",
      fk_cardinality: "mx",
      constraints: [
        {
          primary_column_path: null,
          primary_column: "BOOKNO",
          foreign_column_path: null,
          foreign_column: "BOOKNO",
        },
      ],
      custom_fields: {},
    },
  ],
  unique_keys: [
    {
      name: "PK_INM_BOOKING",
      description: null,
      is_pk: true,
      is_user_defined: false,
      columns: [
        {
          path: null,
          name_without_path: "BOOKNO",
          name: "BOOKNO",
          column_id: 1594,
        },
      ],
      custom_fields: {},
    },
  ],
  triggers: [],
  dependencies: {
    uses: [
      {
        object_name: "INM_BOOKING",
        object_name_show_schema: "dbo.INM_BOOKING",
        object_type: "TABLE",
        object_id: "t69",
        type: "NORMAL",
        object_user_defined: false,
        user_defined: false,
        children: [
          {
            object_name: "ALPHA",
            object_name_show_schema: "dbo.ALPHA",
            object_type: "TABLE",
            object_id: "t412",
            type: "RELATION",
            pk_cardinality: "1x",
            fk_cardinality: "mx",
            object_user_defined: false,
            user_defined: false,
            children: [],
          },
        ],
      },
    ],
    used_by: [
      {
        object_name: "INM_BOOKING",
        object_name_show_schema: "dbo.INM_BOOKING",
        object_type: "TABLE",
        object_id: "t69",
        type: "NORMAL",
        object_user_defined: false,
        user_defined: false,
        children: [
          {
            object_name: "INM_ALERTS",
            object_name_show_schema: "dbo.INM_ALERTS",
            object_type: "TABLE",
            object_id: "t238",
            type: "RELATION",
            pk_cardinality: "1x",
            fk_cardinality: "mx",
            object_user_defined: false,
            user_defined: false,
            children: [],
          },
          {
            object_name: "INM_APPT_REQUESTS",
            object_name_show_schema: "dbo.INM_APPT_REQUESTS",
            object_type: "TABLE",
            object_id: "t246",
            type: "RELATION",
            pk_cardinality: "1x",
            fk_cardinality: "mx",
            object_user_defined: false,
            user_defined: false,
            children: [],
          },
          {
            object_name: "INM_ATTACHMENTS",
            object_name_show_schema: "dbo.INM_ATTACHMENTS",
            object_type: "TABLE",
            object_id: "t252",
            type: "RELATION",
            pk_cardinality: "1x",
            fk_cardinality: "mx",
            object_user_defined: false,
            user_defined: false,
            children: [],
          },
          {
            object_name: "INM_AUDIT",
            object_name_show_schema: "dbo.INM_AUDIT",
            object_type: "TABLE",
            object_id: "t258",
            type: "RELATION",
            pk_cardinality: "1x",
            fk_cardinality: "mx",
            object_user_defined: false,
            user_defined: false,
            children: [],
          },
          {
            object_name: "INM_AUTHORIZED_ITEMS",
            object_name_show_schema: "dbo.INM_AUTHORIZED_ITEMS",
            object_type: "TABLE",
            object_id: "t64",
            type: "RELATION",
            pk_cardinality: "1x",
            fk_cardinality: "mx",
            object_user_defined: false,
            user_defined: false,
            children: [],
          },
          {
            object_name: "INM_BOOKING_SCHEDULED",
            object_name_show_schema: "dbo.INM_BOOKING_SCHEDULED",
            object_type: "TABLE",
            object_id: "t261",
            type: "RELATION",
            pk_cardinality: "1x",
            fk_cardinality: "mx",
            object_user_defined: false,
            user_defined: false,
            children: [],
          },
          {
            object_name: "INM_CELL_LOG",
            object_name_show_schema: "dbo.INM_CELL_LOG",
            object_type: "TABLE",
            object_id: "t267",
            type: "RELATION",
            pk_cardinality: "1x",
            fk_cardinality: "mx",
            object_user_defined: false,
            user_defined: false,
            children: [],
          },
          {
            object_name: "INM_CHARGES",
            object_name_show_schema: "dbo.INM_CHARGES",
            object_type: "TABLE",
            object_id: "t220",
            type: "RELATION",
            pk_cardinality: "1x",
            fk_cardinality: "mx",
            object_user_defined: false,
            user_defined: false,
            children: [],
          },
          {
            object_name: "INM_COMORDER",
            object_name_show_schema: "dbo.INM_COMORDER",
            object_type: "TABLE",
            object_id: "t148",
            type: "RELATION",
            pk_cardinality: "1x",
            fk_cardinality: "mx",
            object_user_defined: false,
            user_defined: false,
            children: [],
          },
          {
            object_name: "INM_COURT_LOG",
            object_name_show_schema: "dbo.INM_COURT_LOG",
            object_type: "TABLE",
            object_id: "t290",
            type: "RELATION",
            pk_cardinality: "1x",
            fk_cardinality: "mx",
            object_user_defined: false,
            user_defined: false,
            children: [],
          },
          {
            object_name: "INM_DISCIPLINARY",
            object_name_show_schema: "dbo.INM_DISCIPLINARY",
            object_type: "TABLE",
            object_id: "t227",
            type: "RELATION",
            pk_cardinality: "1x",
            fk_cardinality: "mx",
            object_user_defined: false,
            user_defined: false,
            children: [],
          },
          {
            object_name: "INM_DISCIPLINARY_HEARINGS",
            object_name_show_schema: "dbo.INM_DISCIPLINARY_HEARINGS",
            object_type: "TABLE",
            object_id: "t233",
            type: "RELATION",
            pk_cardinality: "1x",
            fk_cardinality: "mx",
            object_user_defined: false,
            user_defined: false,
            children: [],
          },
          {
            object_name: "INM_INT_QUESTIONS",
            object_name_show_schema: "dbo.INM_INT_QUESTIONS",
            object_type: "TABLE",
            object_id: "t32",
            type: "RELATION",
            pk_cardinality: "1x",
            fk_cardinality: "mx",
            object_user_defined: false,
            user_defined: false,
            children: [],
          },
          {
            object_name: "INM_INT_SUBQUESTIONS",
            object_name_show_schema: "dbo.INM_INT_SUBQUESTIONS",
            object_type: "TABLE",
            object_id: "t114",
            type: "RELATION",
            pk_cardinality: "1x",
            fk_cardinality: "mx",
            object_user_defined: false,
            user_defined: false,
            children: [],
          },
          {
            object_name: "INM_INTAKE_PROPERTY",
            object_name_show_schema: "dbo.INM_INTAKE_PROPERTY",
            object_type: "TABLE",
            object_id: "t164",
            type: "RELATION",
            pk_cardinality: "1x",
            fk_cardinality: "mx",
            object_user_defined: false,
            user_defined: false,
            children: [],
          },
          {
            object_name: "INM_KEEP_AWAY",
            object_name_show_schema: "dbo.INM_KEEP_AWAY",
            object_type: "TABLE",
            object_id: "t245",
            type: "RELATION",
            pk_cardinality: "1x",
            fk_cardinality: "mx",
            object_user_defined: false,
            user_defined: false,
            children: [],
          },
          {
            object_name: "INM_MAIL_LOG",
            object_name_show_schema: "dbo.INM_MAIL_LOG",
            object_type: "TABLE",
            object_id: "t86",
            type: "RELATION",
            pk_cardinality: "1x",
            fk_cardinality: "mx",
            object_user_defined: false,
            user_defined: false,
            children: [],
          },
          {
            object_name: "INM_MEDIA_LOG",
            object_name_show_schema: "dbo.INM_MEDIA_LOG",
            object_type: "TABLE",
            object_id: "t209",
            type: "RELATION",
            pk_cardinality: "1x",
            fk_cardinality: "mx",
            object_user_defined: false,
            user_defined: false,
            children: [],
          },
          {
            object_name: "INM_MEDICAL_ALLERGIES",
            object_name_show_schema: "dbo.INM_MEDICAL_ALLERGIES",
            object_type: "TABLE",
            object_id: "t212",
            type: "RELATION",
            pk_cardinality: "1x",
            fk_cardinality: "mx",
            object_user_defined: false,
            user_defined: false,
            children: [],
          },
          {
            object_name: "INM_MEDICAL_CHART",
            object_name_show_schema: "dbo.INM_MEDICAL_CHART",
            object_type: "TABLE",
            object_id: "t216",
            type: "RELATION",
            pk_cardinality: "1x",
            fk_cardinality: "mx",
            object_user_defined: false,
            user_defined: false,
            children: [],
          },
          {
            object_name: "INM_MEDICAL_DIET",
            object_name_show_schema: "dbo.INM_MEDICAL_DIET",
            object_type: "TABLE",
            object_id: "t143",
            type: "RELATION",
            pk_cardinality: "1x",
            fk_cardinality: "mx",
            object_user_defined: false,
            user_defined: false,
            children: [],
          },
          {
            object_name: "INM_MEDICAL_GLUCOSE",
            object_name_show_schema: "dbo.INM_MEDICAL_GLUCOSE",
            object_type: "TABLE",
            object_id: "t107",
            type: "RELATION",
            pk_cardinality: "1x",
            fk_cardinality: "mx",
            object_user_defined: false,
            user_defined: false,
            children: [],
          },
          {
            object_name: "INM_MEDICAL_LOG",
            object_name_show_schema: "dbo.INM_MEDICAL_LOG",
            object_type: "TABLE",
            object_id: "t251",
            type: "RELATION",
            pk_cardinality: "1x",
            fk_cardinality: "mx",
            object_user_defined: false,
            user_defined: false,
            children: [],
          },
          {
            object_name: "INM_MEDICAL_TB",
            object_name_show_schema: "dbo.INM_MEDICAL_TB",
            object_type: "TABLE",
            object_id: "t118",
            type: "RELATION",
            pk_cardinality: "1x",
            fk_cardinality: "mx",
            object_user_defined: false,
            user_defined: false,
            children: [],
          },
          {
            object_name: "INM_MEDLIST",
            object_name_show_schema: "dbo.INM_MEDLIST",
            object_type: "TABLE",
            object_id: "t257",
            type: "RELATION",
            pk_cardinality: "1x",
            fk_cardinality: "mx",
            object_user_defined: false,
            user_defined: false,
            children: [],
          },
          {
            object_name: "INM_PEOPLE",
            object_name_show_schema: "dbo.INM_PEOPLE",
            object_type: "TABLE",
            object_id: "t361",
            type: "RELATION",
            pk_cardinality: "1x",
            fk_cardinality: "mx",
            object_user_defined: false,
            user_defined: false,
            children: [],
          },
          {
            object_name: "INM_PEOPLE_LOG",
            object_name_show_schema: "dbo.INM_PEOPLE_LOG",
            object_type: "TABLE",
            object_id: "t370",
            type: "RELATION",
            pk_cardinality: "1x",
            fk_cardinality: "mx",
            object_user_defined: false,
            user_defined: false,
            children: [],
          },
          {
            object_name: "INM_PHONE_ACCESS",
            object_name_show_schema: "dbo.INM_PHONE_ACCESS",
            object_type: "TABLE",
            object_id: "t20",
            type: "RELATION",
            pk_cardinality: "1x",
            fk_cardinality: "mx",
            object_user_defined: false,
            user_defined: false,
            children: [],
          },
          {
            object_name: "INM_PHONE_LOG",
            object_name_show_schema: "dbo.INM_PHONE_LOG",
            object_type: "TABLE",
            object_id: "t411",
            type: "RELATION",
            pk_cardinality: "1x",
            fk_cardinality: "mx",
            object_user_defined: false,
            user_defined: false,
            children: [],
          },
          {
            object_name: "INM_REQUEST",
            object_name_show_schema: "dbo.INM_REQUEST",
            object_type: "TABLE",
            object_id: "t298",
            type: "RELATION",
            pk_cardinality: "1x",
            fk_cardinality: "mx",
            object_user_defined: false,
            user_defined: false,
            children: [],
          },
          {
            object_name: "INM_SHIFT_LOG",
            object_name_show_schema: "dbo.INM_SHIFT_LOG",
            object_type: "TABLE",
            object_id: "t188",
            type: "RELATION",
            pk_cardinality: "1x",
            fk_cardinality: "mx",
            object_user_defined: false,
            user_defined: false,
            children: [],
          },
          {
            object_name: "INM_STAY_CHARGES",
            object_name_show_schema: "dbo.INM_STAY_CHARGES",
            object_type: "TABLE",
            object_id: "t197",
            type: "RELATION",
            pk_cardinality: "1x",
            fk_cardinality: "mx",
            object_user_defined: false,
            user_defined: false,
            children: [],
          },
        ],
      },
    ],
  },
  object_id: "t69",
  name: "INM_BOOKING",
  subtype: "TABLE",
  is_user_defined: false,
  description:
    '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\r\n                <html xmlns="http://www.w3.org/1999/xhtml">\r\n                    <head>\r\n                        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><title>\r\n                        </title>\r\n                        <style type="text/css">\r\n                            .cs2654AE3A{text-align:left;text-indent:0pt;margin:0pt 0pt 0pt 0pt}\r\n                            .cs416E45A4{color:#000000;background-color:transparent;font-family:\'Segoe UI\';font-size:10pt;font-weight:normal;font-style:normal;}\r\n                        </style>\r\n                    </head>\r\n                    <body>\r\n                        <p class="cs2654AE3A"><span class="cs416E45A4">Booking Information</span></p></body>\r\n                </html>',
  summary: [
    {
      field: "Documentation",
      value: { _type: "link", name: "SUN RIDGE SYSTEMS", id: "d1" },
    },
    { field: "Schema", value: "dbo" },
    { field: "Name", value: "INM_BOOKING" },
    { field: "Type", value: "Table" },
  ],
  script: "",
  imported_at: "2024-10-01 02:34",
};
